// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package productallocations

import (
	"context"
)

type Querier interface {
	CreateProductAllocation(ctx context.Context, arg *CreateProductAllocationParams) (*ProductAllocation, error)
	GetProductAllocationByID(ctx context.Context, id int32) (*ProductAllocation, error)
	GetProductsFromProductAllocationsByShopID(ctx context.Context, shopID int32) ([]*GetProductsFromProductAllocationsByShopIDRow, error)
	ListProductAllocationsView(ctx context.Context) ([]*ListProductAllocationsViewRow, error)
	UpdateProductAllocation(ctx context.Context, arg *UpdateProductAllocationParams) (*ProductAllocation, error)
}

var _ Querier = (*Queries)(nil)
