// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package products

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CarPart struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	PartName    string      `db:"part_name" json:"partName"`
	Description pgtype.Text `db:"description" json:"description"`
	IsActive    pgtype.Bool `db:"is_active" json:"isActive"`
	CreatedAt   time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time   `db:"updated_at" json:"updatedAt"`
}

type Claim struct {
	ID                 uuid.UUID   `db:"id" json:"id"`
	WarrantyID         uuid.UUID   `db:"warranty_id" json:"warrantyId"`
	ClaimNo            string      `db:"claim_no" json:"claimNo"`
	Status             string      `db:"status" json:"status"`
	ClaimDate          pgtype.Date `db:"claim_date" json:"claimDate"`
	DamagedImageUrl    string      `db:"damaged_image_url" json:"damagedImageUrl"`
	ResolutionImageUrl string      `db:"resolution_image_url" json:"resolutionImageUrl"`
	Remarks            pgtype.Text `db:"remarks" json:"remarks"`
	CreatedAt          time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt          time.Time   `db:"updated_at" json:"updatedAt"`
}

type ClaimDetail struct {
	ClaimID               uuid.UUID        `db:"claim_id" json:"claimId"`
	ClaimNo               string           `db:"claim_no" json:"claimNo"`
	Status                string           `db:"status" json:"status"`
	ClaimDate             pgtype.Date      `db:"claim_date" json:"claimDate"`
	DamagedImageUrl       string           `db:"damaged_image_url" json:"damagedImageUrl"`
	ResolutionImageUrl    string           `db:"resolution_image_url" json:"resolutionImageUrl"`
	Remarks               pgtype.Text      `db:"remarks" json:"remarks"`
	CreatedAt             time.Time        `db:"created_at" json:"createdAt"`
	UpdatedAt             time.Time        `db:"updated_at" json:"updatedAt"`
	CustomerName          string           `db:"customer_name" json:"customerName"`
	CustomerEmail         string           `db:"customer_email" json:"customerEmail"`
	CustomerContact       string           `db:"customer_contact" json:"customerContact"`
	CarBrand              string           `db:"car_brand" json:"carBrand"`
	CarModel              string           `db:"car_model" json:"carModel"`
	CarPlateNo            string           `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo          string           `db:"car_chassis_no" json:"carChassisNo"`
	WarrantyImageUrl      string           `db:"warranty_image_url" json:"warrantyImageUrl"`
	InstallationDate      pgtype.Date      `db:"installation_date" json:"installationDate"`
	ReferenceNo           string           `db:"reference_no" json:"referenceNo"`
	WarrantyNo            string           `db:"warranty_no" json:"warrantyNo"`
	CarPartName           string           `db:"car_part_name" json:"carPartName"`
	CarPartDescription    pgtype.Text      `db:"car_part_description" json:"carPartDescription"`
	AllocatedFilmQuantity int32            `db:"allocated_film_quantity" json:"allocatedFilmQuantity"`
	FilmAllocatedDate     pgtype.Timestamp `db:"film_allocated_date" json:"filmAllocatedDate"`
	ShopState             string           `db:"shop_state" json:"shopState"`
	ShopCompanyName       string           `db:"shop_company_name" json:"shopCompanyName"`
	ShopName              string           `db:"shop_name" json:"shopName"`
	ShopAddress           string           `db:"shop_address" json:"shopAddress"`
}

type Product struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	ProductNameID  uuid.UUID   `db:"product_name_id" json:"productNameId"`
	ProductBrandID uuid.UUID   `db:"product_brand_id" json:"productBrandId"`
	WarrantyYears  int32       `db:"warranty_years" json:"warrantyYears"`
	FilmSerialNo   string      `db:"film_serial_no" json:"filmSerialNo"`
	FilmQuantity   int32       `db:"film_quantity" json:"filmQuantity"`
	FilmShipmentNo string      `db:"film_shipment_no" json:"filmShipmentNo"`
	IsActive       pgtype.Bool `db:"is_active" json:"isActive"`
	CreatedAt      time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt      time.Time   `db:"updated_at" json:"updatedAt"`
}

type ProductAllocation struct {
	ID            uuid.UUID        `db:"id" json:"id"`
	ProductID     uuid.UUID        `db:"product_id" json:"productId"`
	ShopID        uuid.UUID        `db:"shop_id" json:"shopId"`
	FilmQuantity  int32            `db:"film_quantity" json:"filmQuantity"`
	AllocatedDate pgtype.Timestamp `db:"allocated_date" json:"allocatedDate"`
	CreatedAt     time.Time        `db:"created_at" json:"createdAt"`
	UpdatedAt     time.Time        `db:"updated_at" json:"updatedAt"`
}

type ProductBrand struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	IsActive  pgtype.Bool `db:"is_active" json:"isActive"`
	CreatedAt time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time   `db:"updated_at" json:"updatedAt"`
}

type ProductName struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	ProductSeriesID uuid.UUID   `db:"product_series_id" json:"productSeriesId"`
	Name            string      `db:"name" json:"name"`
	IsActive        pgtype.Bool `db:"is_active" json:"isActive"`
	CreatedAt       time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt       time.Time   `db:"updated_at" json:"updatedAt"`
}

type ProductSeries struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	ProductTypeID uuid.UUID   `db:"product_type_id" json:"productTypeId"`
	Name          string      `db:"name" json:"name"`
	IsActive      pgtype.Bool `db:"is_active" json:"isActive"`
	CreatedAt     time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updatedAt"`
}

type ProductType struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	BrandID   uuid.UUID   `db:"brand_id" json:"brandId"`
	Name      string      `db:"name" json:"name"`
	IsActive  pgtype.Bool `db:"is_active" json:"isActive"`
	CreatedAt time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time   `db:"updated_at" json:"updatedAt"`
}

type Shop struct {
	ID                     uuid.UUID   `db:"id" json:"id"`
	StateID                uuid.UUID   `db:"state_id" json:"stateId"`
	CompanyName            string      `db:"company_name" json:"companyName"`
	CompanyRegistrationNo  string      `db:"company_registration_no" json:"companyRegistrationNo"`
	CompanyLicenseImageUrl string      `db:"company_license_image_url" json:"companyLicenseImageUrl"`
	CompanyEmail           string      `db:"company_email" json:"companyEmail"`
	CompanyContact         string      `db:"company_contact" json:"companyContact"`
	CompanyWebsite         pgtype.Text `db:"company_website" json:"companyWebsite"`
	Name                   string      `db:"name" json:"name"`
	Type                   string      `db:"type" json:"type"`
	Address                string      `db:"address" json:"address"`
	ImageUrl               string      `db:"image_url" json:"imageUrl"`
	PicName                string      `db:"pic_name" json:"picName"`
	PicContact             string      `db:"pic_contact" json:"picContact"`
	PicEmail               string      `db:"pic_email" json:"picEmail"`
	PicPosition            string      `db:"pic_position" json:"picPosition"`
	Username               string      `db:"username" json:"username"`
	LoginHashPassword      string      `db:"login_hash_password" json:"loginHashPassword"`
	IsActive               pgtype.Bool `db:"is_active" json:"isActive"`
	CreatedAt              time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt              time.Time   `db:"updated_at" json:"updatedAt"`
}

type ShopDetail struct {
	ShopID                 uuid.UUID   `db:"shop_id" json:"shopId"`
	CompanyName            string      `db:"company_name" json:"companyName"`
	CompanyRegistrationNo  string      `db:"company_registration_no" json:"companyRegistrationNo"`
	CompanyLicenseImageUrl string      `db:"company_license_image_url" json:"companyLicenseImageUrl"`
	CompanyEmail           string      `db:"company_email" json:"companyEmail"`
	CompanyContact         string      `db:"company_contact" json:"companyContact"`
	CompanyWebsite         pgtype.Text `db:"company_website" json:"companyWebsite"`
	Name                   string      `db:"name" json:"name"`
	Type                   string      `db:"type" json:"type"`
	Address                string      `db:"address" json:"address"`
	ImageUrl               string      `db:"image_url" json:"imageUrl"`
	PicName                string      `db:"pic_name" json:"picName"`
	PicContact             string      `db:"pic_contact" json:"picContact"`
	PicEmail               string      `db:"pic_email" json:"picEmail"`
	PicPosition            string      `db:"pic_position" json:"picPosition"`
	LoginHashPassword      string      `db:"login_hash_password" json:"loginHashPassword"`
	IsActive               pgtype.Bool `db:"is_active" json:"isActive"`
	CreatedAt              time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt              time.Time   `db:"updated_at" json:"updatedAt"`
	StateID                uuid.UUID   `db:"state_id" json:"stateId"`
	StateName              string      `db:"state_name" json:"stateName"`
}

type State struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time `db:"updated_at" json:"updatedAt"`
}

type VwProductDetail struct {
	ProductID      uuid.UUID `db:"product_id" json:"productId"`
	ProductName    string    `db:"product_name" json:"productName"`
	ProductSeries  string    `db:"product_series" json:"productSeries"`
	ProductType    string    `db:"product_type" json:"productType"`
	ProductBrand   string    `db:"product_brand" json:"productBrand"`
	WarrantyYears  int32     `db:"warranty_years" json:"warrantyYears"`
	FilmSerialNo   string    `db:"film_serial_no" json:"filmSerialNo"`
	FilmQuantity   int32     `db:"film_quantity" json:"filmQuantity"`
	FilmShipmentNo string    `db:"film_shipment_no" json:"filmShipmentNo"`
	CreatedAt      time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt      time.Time `db:"updated_at" json:"updatedAt"`
}

type Warranty struct {
	ID                uuid.UUID   `db:"id" json:"id"`
	CustomerName      string      `db:"customer_name" json:"customerName"`
	CustomerEmail     string      `db:"customer_email" json:"customerEmail"`
	CustomerContact   string      `db:"customer_contact" json:"customerContact"`
	CarBrand          string      `db:"car_brand" json:"carBrand"`
	CarModel          string      `db:"car_model" json:"carModel"`
	CarColor          string      `db:"car_color" json:"carColor"`
	CarPlateNo        string      `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo      string      `db:"car_chassis_no" json:"carChassisNo"`
	ShopAllocationsID uuid.UUID   `db:"shop_allocations_id" json:"shopAllocationsId"`
	CarPartsID        uuid.UUID   `db:"car_parts_id" json:"carPartsId"`
	ImageUrl          string      `db:"image_url" json:"imageUrl"`
	InstallationDate  pgtype.Date `db:"installation_date" json:"installationDate"`
	ReferenceNo       string      `db:"reference_no" json:"referenceNo"`
	WarrantyNo        string      `db:"warranty_no" json:"warrantyNo"`
	CreatedAt         time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt         time.Time   `db:"updated_at" json:"updatedAt"`
}

type WarrantyYear struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Years     int32       `db:"years" json:"years"`
	IsActive  pgtype.Bool `db:"is_active" json:"isActive"`
	CreatedAt time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time   `db:"updated_at" json:"updatedAt"`
}
