// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package products

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CarPart struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	PartName    string      `db:"part_name" json:"part_name"`
	Description pgtype.Text `db:"description" json:"description"`
	IsActive    pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt   time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at" json:"updated_at"`
}

type Claim struct {
	ID                 uuid.UUID   `db:"id" json:"id"`
	WarrantyID         uuid.UUID   `db:"warranty_id" json:"warranty_id"`
	ClaimNo            string      `db:"claim_no" json:"claim_no"`
	Status             string      `db:"status" json:"status"`
	ClaimDate          pgtype.Date `db:"claim_date" json:"claim_date"`
	DamagedImageUrl    string      `db:"damaged_image_url" json:"damaged_image_url"`
	ResolutionImageUrl string      `db:"resolution_image_url" json:"resolution_image_url"`
	Remarks            pgtype.Text `db:"remarks" json:"remarks"`
	CreatedAt          time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time   `db:"updated_at" json:"updated_at"`
}

type ClaimDetail struct {
	ClaimID               uuid.UUID        `db:"claim_id" json:"claim_id"`
	ClaimNo               string           `db:"claim_no" json:"claim_no"`
	Status                string           `db:"status" json:"status"`
	ClaimDate             pgtype.Date      `db:"claim_date" json:"claim_date"`
	DamagedImageUrl       string           `db:"damaged_image_url" json:"damaged_image_url"`
	ResolutionImageUrl    string           `db:"resolution_image_url" json:"resolution_image_url"`
	Remarks               pgtype.Text      `db:"remarks" json:"remarks"`
	CreatedAt             time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time        `db:"updated_at" json:"updated_at"`
	CustomerName          string           `db:"customer_name" json:"customer_name"`
	CustomerEmail         string           `db:"customer_email" json:"customer_email"`
	CustomerContact       string           `db:"customer_contact" json:"customer_contact"`
	CarBrand              string           `db:"car_brand" json:"car_brand"`
	CarModel              string           `db:"car_model" json:"car_model"`
	CarPlateNo            string           `db:"car_plate_no" json:"car_plate_no"`
	CarChassisNo          string           `db:"car_chassis_no" json:"car_chassis_no"`
	WarrantyImageUrl      string           `db:"warranty_image_url" json:"warranty_image_url"`
	InstallationDate      pgtype.Date      `db:"installation_date" json:"installation_date"`
	ReferenceNo           string           `db:"reference_no" json:"reference_no"`
	WarrantyNo            string           `db:"warranty_no" json:"warranty_no"`
	CarPartName           string           `db:"car_part_name" json:"car_part_name"`
	CarPartDescription    pgtype.Text      `db:"car_part_description" json:"car_part_description"`
	AllocatedFilmQuantity int32            `db:"allocated_film_quantity" json:"allocated_film_quantity"`
	FilmAllocatedDate     pgtype.Timestamp `db:"film_allocated_date" json:"film_allocated_date"`
	ShopState             string           `db:"shop_state" json:"shop_state"`
	ShopCompanyName       string           `db:"shop_company_name" json:"shop_company_name"`
	ShopName              string           `db:"shop_name" json:"shop_name"`
	ShopAddress           string           `db:"shop_address" json:"shop_address"`
}

type Product struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	ProductNameID  uuid.UUID   `db:"product_name_id" json:"product_name_id"`
	ProductBrandID uuid.UUID   `db:"product_brand_id" json:"product_brand_id"`
	WarrantyYears  int32       `db:"warranty_years" json:"warranty_years"`
	FilmSerialNo   string      `db:"film_serial_no" json:"film_serial_no"`
	FilmQuantity   int32       `db:"film_quantity" json:"film_quantity"`
	FilmShipmentNo string      `db:"film_shipment_no" json:"film_shipment_no"`
	IsActive       pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt      time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at" json:"updated_at"`
}

type ProductAllocation struct {
	ID            uuid.UUID        `db:"id" json:"id"`
	ProductID     uuid.UUID        `db:"product_id" json:"product_id"`
	ShopID        uuid.UUID        `db:"shop_id" json:"shop_id"`
	FilmQuantity  int32            `db:"film_quantity" json:"film_quantity"`
	AllocatedDate pgtype.Timestamp `db:"allocated_date" json:"allocated_date"`
	CreatedAt     time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time        `db:"updated_at" json:"updated_at"`
}

type ProductBrand struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	IsActive  pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt time.Time   `db:"updated_at" json:"updated_at"`
}

type ProductName struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	ProductSeriesID uuid.UUID   `db:"product_series_id" json:"product_series_id"`
	Name            string      `db:"name" json:"name"`
	IsActive        pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt       time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time   `db:"updated_at" json:"updated_at"`
}

type ProductSeries struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	ProductTypeID uuid.UUID   `db:"product_type_id" json:"product_type_id"`
	Name          string      `db:"name" json:"name"`
	IsActive      pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
}

type ProductType struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	BrandID   uuid.UUID   `db:"brand_id" json:"brand_id"`
	Name      string      `db:"name" json:"name"`
	IsActive  pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt time.Time   `db:"updated_at" json:"updated_at"`
}

type Shop struct {
	ID                     uuid.UUID   `db:"id" json:"id"`
	StateID                uuid.UUID   `db:"state_id" json:"state_id"`
	CompanyName            string      `db:"company_name" json:"company_name"`
	CompanyRegistrationNo  string      `db:"company_registration_no" json:"company_registration_no"`
	CompanyLicenseImageUrl string      `db:"company_license_image_url" json:"company_license_image_url"`
	CompanyEmail           string      `db:"company_email" json:"company_email"`
	CompanyContact         string      `db:"company_contact" json:"company_contact"`
	CompanyWebsite         pgtype.Text `db:"company_website" json:"company_website"`
	Name                   string      `db:"name" json:"name"`
	Type                   string      `db:"type" json:"type"`
	Address                string      `db:"address" json:"address"`
	ImageUrl               string      `db:"image_url" json:"image_url"`
	PicName                string      `db:"pic_name" json:"pic_name"`
	PicContact             string      `db:"pic_contact" json:"pic_contact"`
	PicEmail               string      `db:"pic_email" json:"pic_email"`
	PicPosition            string      `db:"pic_position" json:"pic_position"`
	Username               string      `db:"username" json:"username"`
	LoginHashPassword      string      `db:"login_hash_password" json:"login_hash_password"`
	IsActive               pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt              time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt              time.Time   `db:"updated_at" json:"updated_at"`
}

type ShopDetail struct {
	ShopID                 uuid.UUID   `db:"shop_id" json:"shop_id"`
	CompanyName            string      `db:"company_name" json:"company_name"`
	CompanyRegistrationNo  string      `db:"company_registration_no" json:"company_registration_no"`
	CompanyLicenseImageUrl string      `db:"company_license_image_url" json:"company_license_image_url"`
	CompanyEmail           string      `db:"company_email" json:"company_email"`
	CompanyContact         string      `db:"company_contact" json:"company_contact"`
	CompanyWebsite         pgtype.Text `db:"company_website" json:"company_website"`
	Name                   string      `db:"name" json:"name"`
	Type                   string      `db:"type" json:"type"`
	Address                string      `db:"address" json:"address"`
	ImageUrl               string      `db:"image_url" json:"image_url"`
	PicName                string      `db:"pic_name" json:"pic_name"`
	PicContact             string      `db:"pic_contact" json:"pic_contact"`
	PicEmail               string      `db:"pic_email" json:"pic_email"`
	PicPosition            string      `db:"pic_position" json:"pic_position"`
	LoginHashPassword      string      `db:"login_hash_password" json:"login_hash_password"`
	IsActive               pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt              time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt              time.Time   `db:"updated_at" json:"updated_at"`
	StateID                uuid.UUID   `db:"state_id" json:"state_id"`
	StateName              string      `db:"state_name" json:"state_name"`
}

type State struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type VwProductDetail struct {
	ProductID      uuid.UUID `db:"product_id" json:"product_id"`
	ProductName    string    `db:"product_name" json:"product_name"`
	ProductSeries  string    `db:"product_series" json:"product_series"`
	ProductType    string    `db:"product_type" json:"product_type"`
	ProductBrand   string    `db:"product_brand" json:"product_brand"`
	WarrantyYears  int32     `db:"warranty_years" json:"warranty_years"`
	FilmSerialNo   string    `db:"film_serial_no" json:"film_serial_no"`
	FilmQuantity   int32     `db:"film_quantity" json:"film_quantity"`
	FilmShipmentNo string    `db:"film_shipment_no" json:"film_shipment_no"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

type Warranty struct {
	ID                uuid.UUID   `db:"id" json:"id"`
	CustomerName      string      `db:"customer_name" json:"customer_name"`
	CustomerEmail     string      `db:"customer_email" json:"customer_email"`
	CustomerContact   string      `db:"customer_contact" json:"customer_contact"`
	CarBrand          string      `db:"car_brand" json:"car_brand"`
	CarModel          string      `db:"car_model" json:"car_model"`
	CarColor          string      `db:"car_color" json:"car_color"`
	CarPlateNo        string      `db:"car_plate_no" json:"car_plate_no"`
	CarChassisNo      string      `db:"car_chassis_no" json:"car_chassis_no"`
	ShopAllocationsID uuid.UUID   `db:"shop_allocations_id" json:"shop_allocations_id"`
	CarPartsID        uuid.UUID   `db:"car_parts_id" json:"car_parts_id"`
	ImageUrl          string      `db:"image_url" json:"image_url"`
	InstallationDate  pgtype.Date `db:"installation_date" json:"installation_date"`
	ReferenceNo       string      `db:"reference_no" json:"reference_no"`
	WarrantyNo        string      `db:"warranty_no" json:"warranty_no"`
	CreatedAt         time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time   `db:"updated_at" json:"updated_at"`
}

type WarrantyYear struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Years     int32       `db:"years" json:"years"`
	IsActive  pgtype.Bool `db:"is_active" json:"is_active"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt time.Time   `db:"updated_at" json:"updated_at"`
}
