// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.query.sql

package products

import (
	"context"
	"time"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    brand_id,
    type_id,
    series_id,
    name_id,
    warranty_in_months,
    film_serial_number,
    film_quantity,
    shipment_number,
    description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, brand_id, type_id, series_id, name_id, warranty_in_months, film_serial_number, film_quantity, shipment_number, description, is_active, created_at, updated_at
`

type CreateProductParams struct {
	BrandID          int32  `db:"brand_id" json:"brandId"`
	TypeID           int32  `db:"type_id" json:"typeId"`
	SeriesID         int32  `db:"series_id" json:"seriesId"`
	NameID           int32  `db:"name_id" json:"nameId"`
	WarrantyInMonths int32  `db:"warranty_in_months" json:"warrantyInMonths"`
	FilmSerialNumber string `db:"film_serial_number" json:"filmSerialNumber"`
	FilmQuantity     int32  `db:"film_quantity" json:"filmQuantity"`
	ShipmentNumber   string `db:"shipment_number" json:"shipmentNumber"`
	Description      string `db:"description" json:"description"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg *CreateProductParams) (*Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.BrandID,
		arg.TypeID,
		arg.SeriesID,
		arg.NameID,
		arg.WarrantyInMonths,
		arg.FilmSerialNumber,
		arg.FilmQuantity,
		arg.ShipmentNumber,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.TypeID,
		&i.SeriesID,
		&i.NameID,
		&i.WarrantyInMonths,
		&i.FilmSerialNumber,
		&i.FilmQuantity,
		&i.ShipmentNumber,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    id, brand_id, type_id, series_id, name_id, warranty_in_months, film_serial_number, film_quantity, shipment_number, description, is_active, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int32) (*Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.TypeID,
		&i.SeriesID,
		&i.NameID,
		&i.WarrantyInMonths,
		&i.FilmSerialNumber,
		&i.FilmQuantity,
		&i.ShipmentNumber,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProducts = `-- name: GetProducts :many
SELECT
    id, brand_id, type_id, series_id, name_id, warranty_in_months, film_serial_number, film_quantity, shipment_number, description, is_active, created_at, updated_at,
    (SELECT name FROM product_brands WHERE id = p.brand_id) AS brand_name,
    (SELECT name FROM product_types WHERE id = p.type_id) AS type_name,
    (SELECT name FROM product_series WHERE id = p.series_id) AS series_name,
    (SELECT name FROM product_names WHERE id = p.name_id) AS product_name
FROM products p
ORDER BY p.created_at DESC
`

type GetProductsRow struct {
	ID               int32     `db:"id" json:"id"`
	BrandID          int32     `db:"brand_id" json:"brandId"`
	TypeID           int32     `db:"type_id" json:"typeId"`
	SeriesID         int32     `db:"series_id" json:"seriesId"`
	NameID           int32     `db:"name_id" json:"nameId"`
	WarrantyInMonths int32     `db:"warranty_in_months" json:"warrantyInMonths"`
	FilmSerialNumber string    `db:"film_serial_number" json:"filmSerialNumber"`
	FilmQuantity     int32     `db:"film_quantity" json:"filmQuantity"`
	ShipmentNumber   string    `db:"shipment_number" json:"shipmentNumber"`
	Description      string    `db:"description" json:"description"`
	IsActive         bool      `db:"is_active" json:"isActive"`
	CreatedAt        time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt        time.Time `db:"updated_at" json:"updatedAt"`
	BrandName        string    `db:"brand_name" json:"brandName"`
	TypeName         string    `db:"type_name" json:"typeName"`
	SeriesName       string    `db:"series_name" json:"seriesName"`
	ProductName      string    `db:"product_name" json:"productName"`
}

func (q *Queries) GetProducts(ctx context.Context) ([]*GetProductsRow, error) {
	rows, err := q.db.Query(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetProductsRow{}
	for rows.Next() {
		var i GetProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.TypeID,
			&i.SeriesID,
			&i.NameID,
			&i.WarrantyInMonths,
			&i.FilmSerialNumber,
			&i.FilmQuantity,
			&i.ShipmentNumber,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.TypeName,
			&i.SeriesName,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductBrands = `-- name: ListProductBrands :many
SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM product_brands
ORDER BY name
`

func (q *Queries) ListProductBrands(ctx context.Context) ([]*ProductBrand, error) {
	rows, err := q.db.Query(ctx, listProductBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductBrand{}
	for rows.Next() {
		var i ProductBrand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductNames = `-- name: ListProductNames :many
SELECT
    id,
    series_id,
    name,
    description,
    created_at,
    updated_at
FROM product_names
ORDER BY name
`

func (q *Queries) ListProductNames(ctx context.Context) ([]*ProductName, error) {
	rows, err := q.db.Query(ctx, listProductNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductName{}
	for rows.Next() {
		var i ProductName
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductSeries = `-- name: ListProductSeries :many
SELECT
    id,
    type_id,
    name,
    description,
    created_at,
    updated_at
FROM product_series
ORDER BY name
`

func (q *Queries) ListProductSeries(ctx context.Context) ([]*ProductSeries, error) {
	rows, err := q.db.Query(ctx, listProductSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductSeries{}
	for rows.Next() {
		var i ProductSeries
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductTypes = `-- name: ListProductTypes :many
SELECT
    id,
    brand_id,
    name,
    description,
    created_at,
    updated_at
FROM product_types
ORDER BY name
`

func (q *Queries) ListProductTypes(ctx context.Context) ([]*ProductType, error) {
	rows, err := q.db.Query(ctx, listProductTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductType{}
	for rows.Next() {
		var i ProductType
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    brand_id = $2,
    type_id = $3,
    series_id = $4,
    name_id = $5,
    warranty_in_months = $6,
    film_serial_number = $7,
    film_quantity = $8,
    shipment_number = $9,
    description = $10,
    is_active = $11,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, brand_id, type_id, series_id, name_id, warranty_in_months, film_serial_number, film_quantity, shipment_number, description, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ID               int32  `db:"id" json:"id"`
	BrandID          int32  `db:"brand_id" json:"brandId"`
	TypeID           int32  `db:"type_id" json:"typeId"`
	SeriesID         int32  `db:"series_id" json:"seriesId"`
	NameID           int32  `db:"name_id" json:"nameId"`
	WarrantyInMonths int32  `db:"warranty_in_months" json:"warrantyInMonths"`
	FilmSerialNumber string `db:"film_serial_number" json:"filmSerialNumber"`
	FilmQuantity     int32  `db:"film_quantity" json:"filmQuantity"`
	ShipmentNumber   string `db:"shipment_number" json:"shipmentNumber"`
	Description      string `db:"description" json:"description"`
	IsActive         bool   `db:"is_active" json:"isActive"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg *UpdateProductParams) (*Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.BrandID,
		arg.TypeID,
		arg.SeriesID,
		arg.NameID,
		arg.WarrantyInMonths,
		arg.FilmSerialNumber,
		arg.FilmQuantity,
		arg.ShipmentNumber,
		arg.Description,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.TypeID,
		&i.SeriesID,
		&i.NameID,
		&i.WarrantyInMonths,
		&i.FilmSerialNumber,
		&i.FilmQuantity,
		&i.ShipmentNumber,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
