// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_queries.sql

package products

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (product_name_id, product_brand_id, warranty_years, film_serial_no, film_quantity, film_shipment_no)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_name_id, product_brand_id, warranty_years, film_serial_no, film_quantity, film_shipment_no, is_active, created_at, updated_at
`

type CreateProductParams struct {
	ProductNameID  uuid.UUID `db:"product_name_id" json:"productNameId"`
	ProductBrandID uuid.UUID `db:"product_brand_id" json:"productBrandId"`
	WarrantyYears  int32     `db:"warranty_years" json:"warrantyYears"`
	FilmSerialNo   string    `db:"film_serial_no" json:"filmSerialNo"`
	FilmQuantity   int32     `db:"film_quantity" json:"filmQuantity"`
	FilmShipmentNo string    `db:"film_shipment_no" json:"filmShipmentNo"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg *CreateProductParams) (*Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProductNameID,
		arg.ProductBrandID,
		arg.WarrantyYears,
		arg.FilmSerialNo,
		arg.FilmQuantity,
		arg.FilmShipmentNo,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductNameID,
		&i.ProductBrandID,
		&i.WarrantyYears,
		&i.FilmSerialNo,
		&i.FilmQuantity,
		&i.FilmShipmentNo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createProductBrand = `-- name: CreateProductBrand :one
INSERT INTO product_brands (name)
VALUES ($1)
RETURNING id, name, is_active, created_at, updated_at
`

func (q *Queries) CreateProductBrand(ctx context.Context, name string) (*ProductBrand, error) {
	row := q.db.QueryRow(ctx, createProductBrand, name)
	var i ProductBrand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createProductName = `-- name: CreateProductName :one
INSERT INTO product_names (product_series_id, name)
VALUES ($1, $2)
RETURNING id, product_series_id, name, is_active, created_at, updated_at
`

type CreateProductNameParams struct {
	ProductSeriesID uuid.UUID `db:"product_series_id" json:"productSeriesId"`
	Name            string    `db:"name" json:"name"`
}

func (q *Queries) CreateProductName(ctx context.Context, arg *CreateProductNameParams) (*ProductName, error) {
	row := q.db.QueryRow(ctx, createProductName, arg.ProductSeriesID, arg.Name)
	var i ProductName
	err := row.Scan(
		&i.ID,
		&i.ProductSeriesID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createProductSeries = `-- name: CreateProductSeries :one
INSERT INTO product_series (product_type_id, name)
VALUES ($1, $2)
RETURNING id, product_type_id, name, is_active, created_at, updated_at
`

type CreateProductSeriesParams struct {
	ProductTypeID uuid.UUID `db:"product_type_id" json:"productTypeId"`
	Name          string    `db:"name" json:"name"`
}

func (q *Queries) CreateProductSeries(ctx context.Context, arg *CreateProductSeriesParams) (*ProductSeries, error) {
	row := q.db.QueryRow(ctx, createProductSeries, arg.ProductTypeID, arg.Name)
	var i ProductSeries
	err := row.Scan(
		&i.ID,
		&i.ProductTypeID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createProductType = `-- name: CreateProductType :one
INSERT INTO product_types (brand_id, name)
VALUES ($1, $2)
RETURNING id, brand_id, name, is_active, created_at, updated_at
`

type CreateProductTypeParams struct {
	BrandID uuid.UUID `db:"brand_id" json:"brandId"`
	Name    string    `db:"name" json:"name"`
}

func (q *Queries) CreateProductType(ctx context.Context, arg *CreateProductTypeParams) (*ProductType, error) {
	row := q.db.QueryRow(ctx, createProductType, arg.BrandID, arg.Name)
	var i ProductType
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createWarrantyYear = `-- name: CreateWarrantyYear :one
INSERT INTO warranty_years (years)
VALUES ($1)
RETURNING id, years, is_active, created_at, updated_at
`

func (q *Queries) CreateWarrantyYear(ctx context.Context, years int32) (*WarrantyYear, error) {
	row := q.db.QueryRow(ctx, createWarrantyYear, years)
	var i WarrantyYear
	err := row.Scan(
		&i.ID,
		&i.Years,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const deleteProductBrand = `-- name: DeleteProductBrand :exec
DELETE FROM product_brands
WHERE id = $1
`

func (q *Queries) DeleteProductBrand(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductBrand, id)
	return err
}

const deleteProductName = `-- name: DeleteProductName :exec
DELETE FROM product_names
WHERE id = $1
`

func (q *Queries) DeleteProductName(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductName, id)
	return err
}

const deleteProductSeries = `-- name: DeleteProductSeries :exec
DELETE FROM product_series
WHERE id = $1
`

func (q *Queries) DeleteProductSeries(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductSeries, id)
	return err
}

const deleteProductType = `-- name: DeleteProductType :exec
DELETE FROM product_types
WHERE id = $1
`

func (q *Queries) DeleteProductType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductType, id)
	return err
}

const deleteWarrantyYear = `-- name: DeleteWarrantyYear :exec
DELETE FROM warranty_years
WHERE id = $1
`

func (q *Queries) DeleteWarrantyYear(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWarrantyYear, id)
	return err
}

const getProductBrandByID = `-- name: GetProductBrandByID :one
SELECT id, name, is_active, created_at, updated_at FROM product_brands
WHERE id = $1
`

func (q *Queries) GetProductBrandByID(ctx context.Context, id uuid.UUID) (*ProductBrand, error) {
	row := q.db.QueryRow(ctx, getProductBrandByID, id)
	var i ProductBrand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, product_name_id, product_brand_id, warranty_years, film_serial_no, film_quantity, film_shipment_no, is_active, created_at, updated_at FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (*Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductNameID,
		&i.ProductBrandID,
		&i.WarrantyYears,
		&i.FilmSerialNo,
		&i.FilmQuantity,
		&i.FilmShipmentNo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProductDetailsByID = `-- name: GetProductDetailsByID :one
SELECT product_id, product_name, product_series, product_type, product_brand, warranty_years, film_serial_no, film_quantity, film_shipment_no, created_at, updated_at FROM vw_product_details
WHERE product_id = $1
`

func (q *Queries) GetProductDetailsByID(ctx context.Context, productID uuid.UUID) (*VwProductDetail, error) {
	row := q.db.QueryRow(ctx, getProductDetailsByID, productID)
	var i VwProductDetail
	err := row.Scan(
		&i.ProductID,
		&i.ProductName,
		&i.ProductSeries,
		&i.ProductType,
		&i.ProductBrand,
		&i.WarrantyYears,
		&i.FilmSerialNo,
		&i.FilmQuantity,
		&i.FilmShipmentNo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProductNameByID = `-- name: GetProductNameByID :one
SELECT id, product_series_id, name, is_active, created_at, updated_at FROM product_names
WHERE id = $1
`

func (q *Queries) GetProductNameByID(ctx context.Context, id uuid.UUID) (*ProductName, error) {
	row := q.db.QueryRow(ctx, getProductNameByID, id)
	var i ProductName
	err := row.Scan(
		&i.ID,
		&i.ProductSeriesID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProductSeriesByID = `-- name: GetProductSeriesByID :one
SELECT id, product_type_id, name, is_active, created_at, updated_at FROM product_series
WHERE id = $1
`

func (q *Queries) GetProductSeriesByID(ctx context.Context, id uuid.UUID) (*ProductSeries, error) {
	row := q.db.QueryRow(ctx, getProductSeriesByID, id)
	var i ProductSeries
	err := row.Scan(
		&i.ID,
		&i.ProductTypeID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProductTypeByID = `-- name: GetProductTypeByID :one
SELECT id, brand_id, name, is_active, created_at, updated_at FROM product_types
WHERE id = $1
`

func (q *Queries) GetProductTypeByID(ctx context.Context, id uuid.UUID) (*ProductType, error) {
	row := q.db.QueryRow(ctx, getProductTypeByID, id)
	var i ProductType
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWarrantyYearByID = `-- name: GetWarrantyYearByID :one
SELECT id, years, is_active, created_at, updated_at FROM warranty_years
WHERE id = $1
`

func (q *Queries) GetWarrantyYearByID(ctx context.Context, id uuid.UUID) (*WarrantyYear, error) {
	row := q.db.QueryRow(ctx, getWarrantyYearByID, id)
	var i WarrantyYear
	err := row.Scan(
		&i.ID,
		&i.Years,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listProductBrands = `-- name: ListProductBrands :many
SELECT id, name, is_active, created_at, updated_at FROM product_brands
ORDER BY name ASC
`

func (q *Queries) ListProductBrands(ctx context.Context) ([]*ProductBrand, error) {
	rows, err := q.db.Query(ctx, listProductBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductBrand{}
	for rows.Next() {
		var i ProductBrand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductNames = `-- name: ListProductNames :many
SELECT id, product_series_id, name, is_active, created_at, updated_at FROM product_names
ORDER BY name ASC
`

func (q *Queries) ListProductNames(ctx context.Context) ([]*ProductName, error) {
	rows, err := q.db.Query(ctx, listProductNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductName{}
	for rows.Next() {
		var i ProductName
		if err := rows.Scan(
			&i.ID,
			&i.ProductSeriesID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductNamesBySeries = `-- name: ListProductNamesBySeries :many
SELECT id, product_series_id, name, is_active, created_at, updated_at FROM product_names
WHERE product_series_id = $1
`

func (q *Queries) ListProductNamesBySeries(ctx context.Context, productSeriesID uuid.UUID) ([]*ProductName, error) {
	rows, err := q.db.Query(ctx, listProductNamesBySeries, productSeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductName{}
	for rows.Next() {
		var i ProductName
		if err := rows.Scan(
			&i.ID,
			&i.ProductSeriesID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductSeries = `-- name: ListProductSeries :many
SELECT id, product_type_id, name, is_active, created_at, updated_at FROM product_series
ORDER BY name ASC
`

func (q *Queries) ListProductSeries(ctx context.Context) ([]*ProductSeries, error) {
	rows, err := q.db.Query(ctx, listProductSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductSeries{}
	for rows.Next() {
		var i ProductSeries
		if err := rows.Scan(
			&i.ID,
			&i.ProductTypeID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductSeriesByType = `-- name: ListProductSeriesByType :many
SELECT id, product_type_id, name, is_active, created_at, updated_at FROM product_series
WHERE product_type_id = $1
`

func (q *Queries) ListProductSeriesByType(ctx context.Context, productTypeID uuid.UUID) ([]*ProductSeries, error) {
	rows, err := q.db.Query(ctx, listProductSeriesByType, productTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductSeries{}
	for rows.Next() {
		var i ProductSeries
		if err := rows.Scan(
			&i.ID,
			&i.ProductTypeID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductTypes = `-- name: ListProductTypes :many
SELECT id, brand_id, name, is_active, created_at, updated_at FROM product_types
ORDER BY name ASC
`

func (q *Queries) ListProductTypes(ctx context.Context) ([]*ProductType, error) {
	rows, err := q.db.Query(ctx, listProductTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductType{}
	for rows.Next() {
		var i ProductType
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductTypesByBrand = `-- name: ListProductTypesByBrand :many
SELECT id, brand_id, name, is_active, created_at, updated_at FROM product_types
WHERE brand_id = $1
`

func (q *Queries) ListProductTypesByBrand(ctx context.Context, brandID uuid.UUID) ([]*ProductType, error) {
	rows, err := q.db.Query(ctx, listProductTypesByBrand, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductType{}
	for rows.Next() {
		var i ProductType
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, product_name_id, product_brand_id, warranty_years, film_serial_no, film_quantity, film_shipment_no, is_active, created_at, updated_at FROM products
ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]*Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductNameID,
			&i.ProductBrandID,
			&i.WarrantyYears,
			&i.FilmSerialNo,
			&i.FilmQuantity,
			&i.FilmShipmentNo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsWithDetails = `-- name: ListProductsWithDetails :many
SELECT product_id, product_name, product_series, product_type, product_brand, warranty_years, film_serial_no, film_quantity, film_shipment_no, created_at, updated_at FROM vw_product_details
ORDER BY created_at DESC
`

func (q *Queries) ListProductsWithDetails(ctx context.Context) ([]*VwProductDetail, error) {
	rows, err := q.db.Query(ctx, listProductsWithDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*VwProductDetail{}
	for rows.Next() {
		var i VwProductDetail
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.ProductSeries,
			&i.ProductType,
			&i.ProductBrand,
			&i.WarrantyYears,
			&i.FilmSerialNo,
			&i.FilmQuantity,
			&i.FilmShipmentNo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarrantyYears = `-- name: ListWarrantyYears :many
SELECT id, years, is_active, created_at, updated_at FROM warranty_years
ORDER BY years ASC
`

func (q *Queries) ListWarrantyYears(ctx context.Context) ([]*WarrantyYear, error) {
	rows, err := q.db.Query(ctx, listWarrantyYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*WarrantyYear{}
	for rows.Next() {
		var i WarrantyYear
		if err := rows.Scan(
			&i.ID,
			&i.Years,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    product_name_id = $1,
    product_brand_id = $2,
    warranty_years = $3,
    film_serial_no = $4,
    film_quantity = $5,
    film_shipment_no = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7
RETURNING id, product_name_id, product_brand_id, warranty_years, film_serial_no, film_quantity, film_shipment_no, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ProductNameID  uuid.UUID `db:"product_name_id" json:"productNameId"`
	ProductBrandID uuid.UUID `db:"product_brand_id" json:"productBrandId"`
	WarrantyYears  int32     `db:"warranty_years" json:"warrantyYears"`
	FilmSerialNo   string    `db:"film_serial_no" json:"filmSerialNo"`
	FilmQuantity   int32     `db:"film_quantity" json:"filmQuantity"`
	FilmShipmentNo string    `db:"film_shipment_no" json:"filmShipmentNo"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg *UpdateProductParams) (*Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ProductNameID,
		arg.ProductBrandID,
		arg.WarrantyYears,
		arg.FilmSerialNo,
		arg.FilmQuantity,
		arg.FilmShipmentNo,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductNameID,
		&i.ProductBrandID,
		&i.WarrantyYears,
		&i.FilmSerialNo,
		&i.FilmQuantity,
		&i.FilmShipmentNo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateProductBrand = `-- name: UpdateProductBrand :one
UPDATE product_brands
SET 
    name = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, name, is_active, created_at, updated_at
`

type UpdateProductBrandParams struct {
	Name string    `db:"name" json:"name"`
	ID   uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateProductBrand(ctx context.Context, arg *UpdateProductBrandParams) (*ProductBrand, error) {
	row := q.db.QueryRow(ctx, updateProductBrand, arg.Name, arg.ID)
	var i ProductBrand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateProductName = `-- name: UpdateProductName :one
UPDATE product_names
SET 
    name = $1,
    product_series_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, product_series_id, name, is_active, created_at, updated_at
`

type UpdateProductNameParams struct {
	Name            string    `db:"name" json:"name"`
	ProductSeriesID uuid.UUID `db:"product_series_id" json:"productSeriesId"`
	ID              uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateProductName(ctx context.Context, arg *UpdateProductNameParams) (*ProductName, error) {
	row := q.db.QueryRow(ctx, updateProductName, arg.Name, arg.ProductSeriesID, arg.ID)
	var i ProductName
	err := row.Scan(
		&i.ID,
		&i.ProductSeriesID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateProductSeries = `-- name: UpdateProductSeries :one
UPDATE product_series
SET 
    name = $1,
    product_type_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, product_type_id, name, is_active, created_at, updated_at
`

type UpdateProductSeriesParams struct {
	Name          string    `db:"name" json:"name"`
	ProductTypeID uuid.UUID `db:"product_type_id" json:"productTypeId"`
	ID            uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateProductSeries(ctx context.Context, arg *UpdateProductSeriesParams) (*ProductSeries, error) {
	row := q.db.QueryRow(ctx, updateProductSeries, arg.Name, arg.ProductTypeID, arg.ID)
	var i ProductSeries
	err := row.Scan(
		&i.ID,
		&i.ProductTypeID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateProductType = `-- name: UpdateProductType :one
UPDATE product_types
SET 
    brand_id = $1,
    name = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, brand_id, name, is_active, created_at, updated_at
`

type UpdateProductTypeParams struct {
	BrandID uuid.UUID `db:"brand_id" json:"brandId"`
	Name    string    `db:"name" json:"name"`
	ID      uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateProductType(ctx context.Context, arg *UpdateProductTypeParams) (*ProductType, error) {
	row := q.db.QueryRow(ctx, updateProductType, arg.BrandID, arg.Name, arg.ID)
	var i ProductType
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateWarrantyYear = `-- name: UpdateWarrantyYear :one
UPDATE warranty_years
SET
    years = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, years, is_active, created_at, updated_at
`

type UpdateWarrantyYearParams struct {
	Years int32     `db:"years" json:"years"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateWarrantyYear(ctx context.Context, arg *UpdateWarrantyYearParams) (*WarrantyYear, error) {
	row := q.db.QueryRow(ctx, updateWarrantyYear, arg.Years, arg.ID)
	var i WarrantyYear
	err := row.Scan(
		&i.ID,
		&i.Years,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
