// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package products

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg *CreateProductParams) (*Product, error)
	CreateProductBrand(ctx context.Context, name string) (*ProductBrand, error)
	CreateProductName(ctx context.Context, arg *CreateProductNameParams) (*ProductName, error)
	CreateProductSeries(ctx context.Context, arg *CreateProductSeriesParams) (*ProductSeries, error)
	CreateProductType(ctx context.Context, arg *CreateProductTypeParams) (*ProductType, error)
	CreateWarrantyYear(ctx context.Context, years int32) (*WarrantyYear, error)
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteProductBrand(ctx context.Context, id uuid.UUID) error
	DeleteProductName(ctx context.Context, id uuid.UUID) error
	DeleteProductSeries(ctx context.Context, id uuid.UUID) error
	DeleteProductType(ctx context.Context, id uuid.UUID) error
	DeleteWarrantyYear(ctx context.Context, id uuid.UUID) error
	GetProductBrandByID(ctx context.Context, id uuid.UUID) (*ProductBrand, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (*Product, error)
	GetProductDetailsByID(ctx context.Context, productID uuid.UUID) (*VwProductDetail, error)
	GetProductNameByID(ctx context.Context, id uuid.UUID) (*ProductName, error)
	GetProductSeriesByID(ctx context.Context, id uuid.UUID) (*ProductSeries, error)
	GetProductTypeByID(ctx context.Context, id uuid.UUID) (*ProductType, error)
	GetWarrantyYearByID(ctx context.Context, id uuid.UUID) (*WarrantyYear, error)
	ListProductBrands(ctx context.Context) ([]*ProductBrand, error)
	ListProductNames(ctx context.Context) ([]*ProductName, error)
	ListProductNamesBySeries(ctx context.Context, productSeriesID uuid.UUID) ([]*ProductName, error)
	ListProductSeries(ctx context.Context) ([]*ProductSeries, error)
	ListProductSeriesByType(ctx context.Context, productTypeID uuid.UUID) ([]*ProductSeries, error)
	ListProductTypes(ctx context.Context) ([]*ProductType, error)
	ListProducts(ctx context.Context) ([]*Product, error)
	ListProductsWithDetails(ctx context.Context) ([]*VwProductDetail, error)
	ListWarrantyYears(ctx context.Context) ([]*WarrantyYear, error)
	UpdateProduct(ctx context.Context, arg *UpdateProductParams) (*Product, error)
	UpdateProductBrand(ctx context.Context, arg *UpdateProductBrandParams) (*ProductBrand, error)
	UpdateProductName(ctx context.Context, arg *UpdateProductNameParams) (*ProductName, error)
	UpdateProductSeries(ctx context.Context, arg *UpdateProductSeriesParams) (*ProductSeries, error)
	UpdateProductType(ctx context.Context, arg *UpdateProductTypeParams) (*ProductType, error)
	UpdateWarrantyYear(ctx context.Context, arg *UpdateWarrantyYearParams) (*WarrantyYear, error)
}

var _ Querier = (*Queries)(nil)
