resolver 127.0.0.11 valid=30s;

upstream backend {
    server profilm_backend:8080;
}

upstream frontend {
    server profilm_frontend:3000;
}

# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name ewarranty.profilm.com.my www.ewarranty.profilm.com.my;

    location / {
        proxy_pass http://frontend:3000;
    }

    location /api/ {
        proxy_pass http://backend:8080;
    }
}
