version = 5.2.2
archive_dir = /etc/letsencrypt/archive/inikali.com
cert = /etc/letsencrypt/live/inikali.com/cert.pem
privkey = /etc/letsencrypt/live/inikali.com/privkey.pem
chain = /etc/letsencrypt/live/inikali.com/chain.pem
fullchain = /etc/letsencrypt/live/inikali.com/fullchain.pem
[renewalparams]
account = 40da2fd811ecd071757118e7321a26a1
rsa_key_size = 4096
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
inikali.com = /var/www/certbot
