// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package warranties

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCarPart(ctx context.Context, arg *CreateCarPartParams) (*CarPart, error)
	CreateWarranty(ctx context.Context, arg *CreateWarrantyParams) (*Warranty, error)
	DeleteCarPart(ctx context.Context, id uuid.UUID) error
	DeleteWarranty(ctx context.Context, id uuid.UUID) error
	GetCarPartByID(ctx context.Context, id uuid.UUID) (*CarPart, error)
	GetWarrantyByID(ctx context.Context, id uuid.UUID) (*Warranty, error)
	ListCarParts(ctx context.Context) ([]*CarPart, error)
	ListWarranties(ctx context.Context) ([]*Warranty, error)
	UpdateCarPart(ctx context.Context, arg *UpdateCarPartParams) (*CarPart, error)
	UpdateWarranty(ctx context.Context, arg *UpdateWarrantyParams) (*Warranty, error)
}

var _ Querier = (*Queries)(nil)
