// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package warranties

import (
	"context"
)

type Querier interface {
	CreateWarranty(ctx context.Context, arg *CreateWarrantyParams) (*Warranty, error)
	CreateWarrantyPart(ctx context.Context, arg *CreateWarrantyPartParams) (*WarrantyPart, error)
	DeleteWarrantyPart(ctx context.Context, id int32) error
	GetCarParts(ctx context.Context) ([]*CarPart, error)
	GetLatestWarrantyNoByPrefix(ctx context.Context, warrantyNo string) (string, error)
	GetWarrantiesByExactSearch(ctx context.Context, lower string) ([]*GetWarrantiesByExactSearchRow, error)
	GetWarrantiesByShopID(ctx context.Context, shopID int32) ([]*GetWarrantiesByShopIDRow, error)
	GetWarrantyByID(ctx context.Context, id int32) (*Warranty, error)
	GetWarrantyPartByID(ctx context.Context, id int32) (*WarrantyPart, error)
	GetWarrantyPartsByWarrantyID(ctx context.Context, warrantyID int32) ([]*GetWarrantyPartsByWarrantyIDRow, error)
	ListWarranties(ctx context.Context) ([]*ListWarrantiesRow, error)
	UpdateWarranty(ctx context.Context, arg *UpdateWarrantyParams) (*Warranty, error)
	UpdateWarrantyApproval(ctx context.Context, arg *UpdateWarrantyApprovalParams) (*Warranty, error)
	UpdateWarrantyPart(ctx context.Context, arg *UpdateWarrantyPartParams) (*WarrantyPart, error)
	UpdateWarrantyPartApproval(ctx context.Context, arg *UpdateWarrantyPartApprovalParams) (*WarrantyPart, error)
}

var _ Querier = (*Queries)(nil)
