// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warranties.query.sql

package warranties

import (
	"context"
	"time"
)

const createWarranty = `-- name: CreateWarranty :one
INSERT INTO warranties (
    shop_id,
    client_name,
    client_contact,
    client_email,
    car_brand,
    car_model,
    car_colour,
    car_plate_no,
    car_chassis_no,
    installation_date,
    reference_no,
    warranty_no,
    invoice_attachment_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, is_approved, created_at, updated_at
`

type CreateWarrantyParams struct {
	ShopID               int32     `db:"shop_id" json:"shopId"`
	ClientName           string    `db:"client_name" json:"clientName"`
	ClientContact        string    `db:"client_contact" json:"clientContact"`
	ClientEmail          string    `db:"client_email" json:"clientEmail"`
	CarBrand             string    `db:"car_brand" json:"carBrand"`
	CarModel             string    `db:"car_model" json:"carModel"`
	CarColour            string    `db:"car_colour" json:"carColour"`
	CarPlateNo           string    `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo         string    `db:"car_chassis_no" json:"carChassisNo"`
	InstallationDate     time.Time `db:"installation_date" json:"installationDate"`
	ReferenceNo          *string   `db:"reference_no" json:"referenceNo"`
	WarrantyNo           string    `db:"warranty_no" json:"warrantyNo"`
	InvoiceAttachmentUrl string    `db:"invoice_attachment_url" json:"invoiceAttachmentUrl"`
}

func (q *Queries) CreateWarranty(ctx context.Context, arg *CreateWarrantyParams) (*Warranty, error) {
	row := q.db.QueryRow(ctx, createWarranty,
		arg.ShopID,
		arg.ClientName,
		arg.ClientContact,
		arg.ClientEmail,
		arg.CarBrand,
		arg.CarModel,
		arg.CarColour,
		arg.CarPlateNo,
		arg.CarChassisNo,
		arg.InstallationDate,
		arg.ReferenceNo,
		arg.WarrantyNo,
		arg.InvoiceAttachmentUrl,
	)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ClientName,
		&i.ClientContact,
		&i.ClientEmail,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColour,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.InvoiceAttachmentUrl,
		&i.IsActive,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createWarrantyPart = `-- name: CreateWarrantyPart :one
INSERT INTO warranty_parts (
    warranty_id,
    product_allocation_id,
    car_part_id,
    installation_image_url
) VALUES
    ( $1, $2, $3, $4 )
RETURNING id, warranty_id, product_allocation_id, car_part_id, installation_image_url, is_approved, created_at, updated_at
`

type CreateWarrantyPartParams struct {
	WarrantyID           int32  `db:"warranty_id" json:"warrantyId"`
	ProductAllocationID  int32  `db:"product_allocation_id" json:"productAllocationId"`
	CarPartID            int32  `db:"car_part_id" json:"carPartId"`
	InstallationImageUrl string `db:"installation_image_url" json:"installationImageUrl"`
}

func (q *Queries) CreateWarrantyPart(ctx context.Context, arg *CreateWarrantyPartParams) (*WarrantyPart, error) {
	row := q.db.QueryRow(ctx, createWarrantyPart,
		arg.WarrantyID,
		arg.ProductAllocationID,
		arg.CarPartID,
		arg.InstallationImageUrl,
	)
	var i WarrantyPart
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ProductAllocationID,
		&i.CarPartID,
		&i.InstallationImageUrl,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCarParts = `-- name: GetCarParts :many
SELECT
    id, name, code, description, created_at, updated_at
FROM car_parts
ORDER BY name ASC
`

func (q *Queries) GetCarParts(ctx context.Context) ([]*CarPart, error) {
	rows, err := q.db.Query(ctx, getCarParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CarPart{}
	for rows.Next() {
		var i CarPart
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestWarrantyNoByPrefix = `-- name: GetLatestWarrantyNoByPrefix :one
SELECT
    warranty_no
FROM warranties
WHERE warranty_no LIKE $1
ORDER BY warranty_no DESC
LIMIT 1
`

func (q *Queries) GetLatestWarrantyNoByPrefix(ctx context.Context, warrantyNo string) (string, error) {
	row := q.db.QueryRow(ctx, getLatestWarrantyNoByPrefix, warrantyNo)
	var warranty_no string
	err := row.Scan(&warranty_no)
	return warranty_no, err
}

const getWarrantiesByCarPlateNo = `-- name: GetWarrantiesByCarPlateNo :many
SELECT
    id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, is_approved, created_at, updated_at
FROM warranties
WHERE car_plate_no = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWarrantiesByCarPlateNo(ctx context.Context, carPlateNo string) ([]*Warranty, error) {
	rows, err := q.db.Query(ctx, getWarrantiesByCarPlateNo, carPlateNo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ClientName,
			&i.ClientContact,
			&i.ClientEmail,
			&i.CarBrand,
			&i.CarModel,
			&i.CarColour,
			&i.CarPlateNo,
			&i.CarChassisNo,
			&i.InstallationDate,
			&i.ReferenceNo,
			&i.WarrantyNo,
			&i.InvoiceAttachmentUrl,
			&i.IsActive,
			&i.IsApproved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarrantiesBySearchTerm = `-- name: GetWarrantiesBySearchTerm :many
SELECT
    id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, is_approved, created_at, updated_at
FROM warranties
WHERE car_plate_no ILIKE '%' || $1 || '%'
   OR warranty_no ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
`

func (q *Queries) GetWarrantiesBySearchTerm(ctx context.Context, dollar_1 *string) ([]*Warranty, error) {
	rows, err := q.db.Query(ctx, getWarrantiesBySearchTerm, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ClientName,
			&i.ClientContact,
			&i.ClientEmail,
			&i.CarBrand,
			&i.CarModel,
			&i.CarColour,
			&i.CarPlateNo,
			&i.CarChassisNo,
			&i.InstallationDate,
			&i.ReferenceNo,
			&i.WarrantyNo,
			&i.InvoiceAttachmentUrl,
			&i.IsActive,
			&i.IsApproved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarrantiesByShopID = `-- name: GetWarrantiesByShopID :many
SELECT
    id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, is_approved, created_at, updated_at
FROM warranties
WHERE shop_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWarrantiesByShopID(ctx context.Context, shopID int32) ([]*Warranty, error) {
	rows, err := q.db.Query(ctx, getWarrantiesByShopID, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ClientName,
			&i.ClientContact,
			&i.ClientEmail,
			&i.CarBrand,
			&i.CarModel,
			&i.CarColour,
			&i.CarPlateNo,
			&i.CarChassisNo,
			&i.InstallationDate,
			&i.ReferenceNo,
			&i.WarrantyNo,
			&i.InvoiceAttachmentUrl,
			&i.IsActive,
			&i.IsApproved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarrantyByID = `-- name: GetWarrantyByID :one
SELECT
    id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, is_approved, created_at, updated_at
FROM warranties
WHERE id = $1
`

func (q *Queries) GetWarrantyByID(ctx context.Context, id int32) (*Warranty, error) {
	row := q.db.QueryRow(ctx, getWarrantyByID, id)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ClientName,
		&i.ClientContact,
		&i.ClientEmail,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColour,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.InvoiceAttachmentUrl,
		&i.IsActive,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWarrantyByWarrantyNo = `-- name: GetWarrantyByWarrantyNo :one
SELECT
    id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, is_approved, created_at, updated_at
FROM warranties
WHERE warranty_no = $1
`

func (q *Queries) GetWarrantyByWarrantyNo(ctx context.Context, warrantyNo string) (*Warranty, error) {
	row := q.db.QueryRow(ctx, getWarrantyByWarrantyNo, warrantyNo)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ClientName,
		&i.ClientContact,
		&i.ClientEmail,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColour,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.InvoiceAttachmentUrl,
		&i.IsActive,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWarrantyPartsByWarrantyID = `-- name: GetWarrantyPartsByWarrantyID :many
SELECT
    id, warranty_id, product_allocation_id, car_part_id, installation_image_url, is_approved, created_at, updated_at
FROM warranty_parts
WHERE warranty_id = $1
`

func (q *Queries) GetWarrantyPartsByWarrantyID(ctx context.Context, warrantyID int32) ([]*WarrantyPart, error) {
	rows, err := q.db.Query(ctx, getWarrantyPartsByWarrantyID, warrantyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*WarrantyPart{}
	for rows.Next() {
		var i WarrantyPart
		if err := rows.Scan(
			&i.ID,
			&i.WarrantyID,
			&i.ProductAllocationID,
			&i.CarPartID,
			&i.InstallationImageUrl,
			&i.IsApproved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarranties = `-- name: ListWarranties :many
SELECT
    id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, is_approved, created_at, updated_at
FROM warranties
ORDER BY created_at DESC
`

func (q *Queries) ListWarranties(ctx context.Context) ([]*Warranty, error) {
	rows, err := q.db.Query(ctx, listWarranties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ClientName,
			&i.ClientContact,
			&i.ClientEmail,
			&i.CarBrand,
			&i.CarModel,
			&i.CarColour,
			&i.CarPlateNo,
			&i.CarChassisNo,
			&i.InstallationDate,
			&i.ReferenceNo,
			&i.WarrantyNo,
			&i.InvoiceAttachmentUrl,
			&i.IsActive,
			&i.IsApproved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarranty = `-- name: UpdateWarranty :one
UPDATE warranties
SET
    client_name = $2,
    client_contact = $3,
    client_email = $4,
    car_brand = $5,
    car_model = $6,
    car_colour = $7,
    car_plate_no = $8,
    car_chassis_no = $9,
    installation_date = $10,
    reference_no = $11,
    invoice_attachment_url = $12,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, is_approved, created_at, updated_at
`

type UpdateWarrantyParams struct {
	ID                   int32     `db:"id" json:"id"`
	ClientName           string    `db:"client_name" json:"clientName"`
	ClientContact        string    `db:"client_contact" json:"clientContact"`
	ClientEmail          string    `db:"client_email" json:"clientEmail"`
	CarBrand             string    `db:"car_brand" json:"carBrand"`
	CarModel             string    `db:"car_model" json:"carModel"`
	CarColour            string    `db:"car_colour" json:"carColour"`
	CarPlateNo           string    `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo         string    `db:"car_chassis_no" json:"carChassisNo"`
	InstallationDate     time.Time `db:"installation_date" json:"installationDate"`
	ReferenceNo          *string   `db:"reference_no" json:"referenceNo"`
	InvoiceAttachmentUrl string    `db:"invoice_attachment_url" json:"invoiceAttachmentUrl"`
}

func (q *Queries) UpdateWarranty(ctx context.Context, arg *UpdateWarrantyParams) (*Warranty, error) {
	row := q.db.QueryRow(ctx, updateWarranty,
		arg.ID,
		arg.ClientName,
		arg.ClientContact,
		arg.ClientEmail,
		arg.CarBrand,
		arg.CarModel,
		arg.CarColour,
		arg.CarPlateNo,
		arg.CarChassisNo,
		arg.InstallationDate,
		arg.ReferenceNo,
		arg.InvoiceAttachmentUrl,
	)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ClientName,
		&i.ClientContact,
		&i.ClientEmail,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColour,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.InvoiceAttachmentUrl,
		&i.IsActive,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateWarrantyApproval = `-- name: UpdateWarrantyApproval :one
UPDATE warranties
SET
    is_approved = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, is_approved, created_at, updated_at
`

type UpdateWarrantyApprovalParams struct {
	ID         int32 `db:"id" json:"id"`
	IsApproved bool  `db:"is_approved" json:"isApproved"`
}

func (q *Queries) UpdateWarrantyApproval(ctx context.Context, arg *UpdateWarrantyApprovalParams) (*Warranty, error) {
	row := q.db.QueryRow(ctx, updateWarrantyApproval, arg.ID, arg.IsApproved)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ClientName,
		&i.ClientContact,
		&i.ClientEmail,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColour,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.InvoiceAttachmentUrl,
		&i.IsActive,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateWarrantyPart = `-- name: UpdateWarrantyPart :one
UPDATE warranty_parts
SET
    warranty_id = $2,
    car_part_id = $3,
    product_allocation_id = $4,
    installation_image_url = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, warranty_id, product_allocation_id, car_part_id, installation_image_url, is_approved, created_at, updated_at
`

type UpdateWarrantyPartParams struct {
	ID                   int32  `db:"id" json:"id"`
	WarrantyID           int32  `db:"warranty_id" json:"warrantyId"`
	CarPartID            int32  `db:"car_part_id" json:"carPartId"`
	ProductAllocationID  int32  `db:"product_allocation_id" json:"productAllocationId"`
	InstallationImageUrl string `db:"installation_image_url" json:"installationImageUrl"`
}

func (q *Queries) UpdateWarrantyPart(ctx context.Context, arg *UpdateWarrantyPartParams) (*WarrantyPart, error) {
	row := q.db.QueryRow(ctx, updateWarrantyPart,
		arg.ID,
		arg.WarrantyID,
		arg.CarPartID,
		arg.ProductAllocationID,
		arg.InstallationImageUrl,
	)
	var i WarrantyPart
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ProductAllocationID,
		&i.CarPartID,
		&i.InstallationImageUrl,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateWarrantyPartApproval = `-- name: UpdateWarrantyPartApproval :one
UPDATE warranty_parts
SET
    is_approved = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE warranty_id = $1 AND car_part_id = $3
RETURNING id, warranty_id, product_allocation_id, car_part_id, installation_image_url, is_approved, created_at, updated_at
`

type UpdateWarrantyPartApprovalParams struct {
	WarrantyID int32 `db:"warranty_id" json:"warrantyId"`
	IsApproved bool  `db:"is_approved" json:"isApproved"`
	CarPartID  int32 `db:"car_part_id" json:"carPartId"`
}

func (q *Queries) UpdateWarrantyPartApproval(ctx context.Context, arg *UpdateWarrantyPartApprovalParams) (*WarrantyPart, error) {
	row := q.db.QueryRow(ctx, updateWarrantyPartApproval, arg.WarrantyID, arg.IsApproved, arg.CarPartID)
	var i WarrantyPart
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ProductAllocationID,
		&i.CarPartID,
		&i.InstallationImageUrl,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
