// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warranties.query.sql

package warranties

import (
	"context"
	"time"
)

const createWarranty = `-- name: CreateWarranty :one
INSERT INTO warranties (
    shop_id,
    client_name,
    client_contact,
    client_email,
    car_brand,
    car_model,
    car_colour,
    car_plate_no,
    car_chassis_no,
    installation_date,
    reference_no,
    warranty_no,
    invoice_attachment_url,
    remarks
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, approval_status, remarks, created_at, updated_at
`

type CreateWarrantyParams struct {
	ShopID               int32     `db:"shop_id" json:"shopId"`
	ClientName           string    `db:"client_name" json:"clientName"`
	ClientContact        string    `db:"client_contact" json:"clientContact"`
	ClientEmail          string    `db:"client_email" json:"clientEmail"`
	CarBrand             string    `db:"car_brand" json:"carBrand"`
	CarModel             string    `db:"car_model" json:"carModel"`
	CarColour            string    `db:"car_colour" json:"carColour"`
	CarPlateNo           string    `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo         string    `db:"car_chassis_no" json:"carChassisNo"`
	InstallationDate     time.Time `db:"installation_date" json:"installationDate"`
	ReferenceNo          *string   `db:"reference_no" json:"referenceNo"`
	WarrantyNo           string    `db:"warranty_no" json:"warrantyNo"`
	InvoiceAttachmentUrl string    `db:"invoice_attachment_url" json:"invoiceAttachmentUrl"`
	Remarks              *string   `db:"remarks" json:"remarks"`
}

func (q *Queries) CreateWarranty(ctx context.Context, arg *CreateWarrantyParams) (*Warranty, error) {
	row := q.db.QueryRow(ctx, createWarranty,
		arg.ShopID,
		arg.ClientName,
		arg.ClientContact,
		arg.ClientEmail,
		arg.CarBrand,
		arg.CarModel,
		arg.CarColour,
		arg.CarPlateNo,
		arg.CarChassisNo,
		arg.InstallationDate,
		arg.ReferenceNo,
		arg.WarrantyNo,
		arg.InvoiceAttachmentUrl,
		arg.Remarks,
	)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ClientName,
		&i.ClientContact,
		&i.ClientEmail,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColour,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.InvoiceAttachmentUrl,
		&i.IsActive,
		&i.ApprovalStatus,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createWarrantyPart = `-- name: CreateWarrantyPart :one
INSERT INTO warranty_parts (
    warranty_id,
    car_part_id,
    product_allocation_id,
    installation_image_url,
    remarks
) VALUES
    ( $1, $2, $3, $4, $5 )
RETURNING id, warranty_id, product_allocation_id, car_part_id, installation_image_url, approval_status, remarks, created_at, updated_at
`

type CreateWarrantyPartParams struct {
	WarrantyID           int32   `db:"warranty_id" json:"warrantyId"`
	CarPartID            int32   `db:"car_part_id" json:"carPartId"`
	ProductAllocationID  int32   `db:"product_allocation_id" json:"productAllocationId"`
	InstallationImageUrl string  `db:"installation_image_url" json:"installationImageUrl"`
	Remarks              *string `db:"remarks" json:"remarks"`
}

func (q *Queries) CreateWarrantyPart(ctx context.Context, arg *CreateWarrantyPartParams) (*WarrantyPart, error) {
	row := q.db.QueryRow(ctx, createWarrantyPart,
		arg.WarrantyID,
		arg.CarPartID,
		arg.ProductAllocationID,
		arg.InstallationImageUrl,
		arg.Remarks,
	)
	var i WarrantyPart
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ProductAllocationID,
		&i.CarPartID,
		&i.InstallationImageUrl,
		&i.ApprovalStatus,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteWarrantyPart = `-- name: DeleteWarrantyPart :exec
DELETE FROM warranty_parts
WHERE id = $1
`

func (q *Queries) DeleteWarrantyPart(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteWarrantyPart, id)
	return err
}

const getCarParts = `-- name: GetCarParts :many
SELECT
    id, name, code, description, created_at, updated_at
FROM car_parts
ORDER BY name ASC
`

func (q *Queries) GetCarParts(ctx context.Context) ([]*CarPart, error) {
	rows, err := q.db.Query(ctx, getCarParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CarPart{}
	for rows.Next() {
		var i CarPart
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestWarrantyNoByPrefix = `-- name: GetLatestWarrantyNoByPrefix :one
SELECT
    warranty_no
FROM warranties
WHERE warranty_no LIKE $1
ORDER BY warranty_no DESC
LIMIT 1
`

func (q *Queries) GetLatestWarrantyNoByPrefix(ctx context.Context, warrantyNo string) (string, error) {
	row := q.db.QueryRow(ctx, getLatestWarrantyNoByPrefix, warrantyNo)
	var warranty_no string
	err := row.Scan(&warranty_no)
	return warranty_no, err
}

const getWarrantiesByExactSearch = `-- name: GetWarrantiesByExactSearch :many
SELECT DISTINCT
    w.id, w.shop_id, w.client_name, w.client_contact, w.client_email, w.car_brand, w.car_model, w.car_colour, w.car_plate_no, w.car_chassis_no, w.installation_date, w.reference_no, w.warranty_no, w.invoice_attachment_url, w.is_active, w.approval_status, w.remarks, w.created_at, w.updated_at,
    s.shop_name,
    s.branch_code
FROM warranties w
JOIN shops s ON w.shop_id = s.id
LEFT JOIN warranty_parts wp ON w.id = wp.warranty_id
WHERE LOWER(w.warranty_no) = LOWER($1)
   OR LOWER(w.car_plate_no) = LOWER($1)
ORDER BY w.created_at DESC
`

type GetWarrantiesByExactSearchRow struct {
	ID                   int32                  `db:"id" json:"id"`
	ShopID               int32                  `db:"shop_id" json:"shopId"`
	ClientName           string                 `db:"client_name" json:"clientName"`
	ClientContact        string                 `db:"client_contact" json:"clientContact"`
	ClientEmail          string                 `db:"client_email" json:"clientEmail"`
	CarBrand             string                 `db:"car_brand" json:"carBrand"`
	CarModel             string                 `db:"car_model" json:"carModel"`
	CarColour            string                 `db:"car_colour" json:"carColour"`
	CarPlateNo           string                 `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo         string                 `db:"car_chassis_no" json:"carChassisNo"`
	InstallationDate     time.Time              `db:"installation_date" json:"installationDate"`
	ReferenceNo          *string                `db:"reference_no" json:"referenceNo"`
	WarrantyNo           string                 `db:"warranty_no" json:"warrantyNo"`
	InvoiceAttachmentUrl string                 `db:"invoice_attachment_url" json:"invoiceAttachmentUrl"`
	IsActive             bool                   `db:"is_active" json:"isActive"`
	ApprovalStatus       WarrantyApprovalStatus `db:"approval_status" json:"approvalStatus"`
	Remarks              *string                `db:"remarks" json:"remarks"`
	CreatedAt            time.Time              `db:"created_at" json:"createdAt"`
	UpdatedAt            time.Time              `db:"updated_at" json:"updatedAt"`
	ShopName             string                 `db:"shop_name" json:"shopName"`
	BranchCode           string                 `db:"branch_code" json:"branchCode"`
}

func (q *Queries) GetWarrantiesByExactSearch(ctx context.Context, lower string) ([]*GetWarrantiesByExactSearchRow, error) {
	rows, err := q.db.Query(ctx, getWarrantiesByExactSearch, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetWarrantiesByExactSearchRow{}
	for rows.Next() {
		var i GetWarrantiesByExactSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ClientName,
			&i.ClientContact,
			&i.ClientEmail,
			&i.CarBrand,
			&i.CarModel,
			&i.CarColour,
			&i.CarPlateNo,
			&i.CarChassisNo,
			&i.InstallationDate,
			&i.ReferenceNo,
			&i.WarrantyNo,
			&i.InvoiceAttachmentUrl,
			&i.IsActive,
			&i.ApprovalStatus,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShopName,
			&i.BranchCode,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarrantiesByShopID = `-- name: GetWarrantiesByShopID :many
SELECT
    w.id, w.shop_id, w.client_name, w.client_contact, w.client_email, w.car_brand, w.car_model, w.car_colour, w.car_plate_no, w.car_chassis_no, w.installation_date, w.reference_no, w.warranty_no, w.invoice_attachment_url, w.is_active, w.approval_status, w.remarks, w.created_at, w.updated_at,
    s.shop_name,
    s.branch_code
FROM warranties w
JOIN shops s ON w.shop_id = s.id
WHERE w.shop_id = $1
ORDER BY w.created_at DESC
`

type GetWarrantiesByShopIDRow struct {
	ID                   int32                  `db:"id" json:"id"`
	ShopID               int32                  `db:"shop_id" json:"shopId"`
	ClientName           string                 `db:"client_name" json:"clientName"`
	ClientContact        string                 `db:"client_contact" json:"clientContact"`
	ClientEmail          string                 `db:"client_email" json:"clientEmail"`
	CarBrand             string                 `db:"car_brand" json:"carBrand"`
	CarModel             string                 `db:"car_model" json:"carModel"`
	CarColour            string                 `db:"car_colour" json:"carColour"`
	CarPlateNo           string                 `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo         string                 `db:"car_chassis_no" json:"carChassisNo"`
	InstallationDate     time.Time              `db:"installation_date" json:"installationDate"`
	ReferenceNo          *string                `db:"reference_no" json:"referenceNo"`
	WarrantyNo           string                 `db:"warranty_no" json:"warrantyNo"`
	InvoiceAttachmentUrl string                 `db:"invoice_attachment_url" json:"invoiceAttachmentUrl"`
	IsActive             bool                   `db:"is_active" json:"isActive"`
	ApprovalStatus       WarrantyApprovalStatus `db:"approval_status" json:"approvalStatus"`
	Remarks              *string                `db:"remarks" json:"remarks"`
	CreatedAt            time.Time              `db:"created_at" json:"createdAt"`
	UpdatedAt            time.Time              `db:"updated_at" json:"updatedAt"`
	ShopName             string                 `db:"shop_name" json:"shopName"`
	BranchCode           string                 `db:"branch_code" json:"branchCode"`
}

func (q *Queries) GetWarrantiesByShopID(ctx context.Context, shopID int32) ([]*GetWarrantiesByShopIDRow, error) {
	rows, err := q.db.Query(ctx, getWarrantiesByShopID, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetWarrantiesByShopIDRow{}
	for rows.Next() {
		var i GetWarrantiesByShopIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ClientName,
			&i.ClientContact,
			&i.ClientEmail,
			&i.CarBrand,
			&i.CarModel,
			&i.CarColour,
			&i.CarPlateNo,
			&i.CarChassisNo,
			&i.InstallationDate,
			&i.ReferenceNo,
			&i.WarrantyNo,
			&i.InvoiceAttachmentUrl,
			&i.IsActive,
			&i.ApprovalStatus,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShopName,
			&i.BranchCode,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarrantyByID = `-- name: GetWarrantyByID :one
SELECT
    id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, approval_status, remarks, created_at, updated_at
FROM warranties
WHERE id = $1
`

func (q *Queries) GetWarrantyByID(ctx context.Context, id int32) (*Warranty, error) {
	row := q.db.QueryRow(ctx, getWarrantyByID, id)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ClientName,
		&i.ClientContact,
		&i.ClientEmail,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColour,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.InvoiceAttachmentUrl,
		&i.IsActive,
		&i.ApprovalStatus,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWarrantyPartByID = `-- name: GetWarrantyPartByID :one
SELECT
    id, warranty_id, product_allocation_id, car_part_id, installation_image_url, approval_status, remarks, created_at, updated_at
FROM warranty_parts
WHERE id = $1
`

func (q *Queries) GetWarrantyPartByID(ctx context.Context, id int32) (*WarrantyPart, error) {
	row := q.db.QueryRow(ctx, getWarrantyPartByID, id)
	var i WarrantyPart
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ProductAllocationID,
		&i.CarPartID,
		&i.InstallationImageUrl,
		&i.ApprovalStatus,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWarrantyPartsByWarrantyID = `-- name: GetWarrantyPartsByWarrantyID :many
SELECT
    wp.id, wp.warranty_id, wp.product_allocation_id, wp.car_part_id, wp.installation_image_url, wp.approval_status, wp.remarks, wp.created_at, wp.updated_at,
    cp.name AS car_part_name,
    cp.code AS car_part_code,
    p.film_serial_number,
    p.warranty_in_months,
    pb.name AS product_brand,
    pt.name AS product_type,
    ps.name AS product_series,
    pn.name AS product_name
FROM warranty_parts wp
JOIN car_parts cp ON wp.car_part_id = cp.id
JOIN product_allocations pa ON wp.product_allocation_id = pa.id
JOIN products p ON pa.product_id = p.id
JOIN product_brands pb ON p.brand_id = pb.id
JOIN product_types pt ON p.type_id = pt.id
JOIN product_series ps ON p.series_id = ps.id
JOIN product_names pn ON p.name_id = pn.id
WHERE wp.warranty_id = $1
`

type GetWarrantyPartsByWarrantyIDRow struct {
	ID                   int32                  `db:"id" json:"id"`
	WarrantyID           int32                  `db:"warranty_id" json:"warrantyId"`
	ProductAllocationID  int32                  `db:"product_allocation_id" json:"productAllocationId"`
	CarPartID            int32                  `db:"car_part_id" json:"carPartId"`
	InstallationImageUrl string                 `db:"installation_image_url" json:"installationImageUrl"`
	ApprovalStatus       WarrantyApprovalStatus `db:"approval_status" json:"approvalStatus"`
	Remarks              *string                `db:"remarks" json:"remarks"`
	CreatedAt            time.Time              `db:"created_at" json:"createdAt"`
	UpdatedAt            time.Time              `db:"updated_at" json:"updatedAt"`
	CarPartName          string                 `db:"car_part_name" json:"carPartName"`
	CarPartCode          string                 `db:"car_part_code" json:"carPartCode"`
	FilmSerialNumber     string                 `db:"film_serial_number" json:"filmSerialNumber"`
	WarrantyInMonths     int32                  `db:"warranty_in_months" json:"warrantyInMonths"`
	ProductBrand         string                 `db:"product_brand" json:"productBrand"`
	ProductType          string                 `db:"product_type" json:"productType"`
	ProductSeries        string                 `db:"product_series" json:"productSeries"`
	ProductName          string                 `db:"product_name" json:"productName"`
}

func (q *Queries) GetWarrantyPartsByWarrantyID(ctx context.Context, warrantyID int32) ([]*GetWarrantyPartsByWarrantyIDRow, error) {
	rows, err := q.db.Query(ctx, getWarrantyPartsByWarrantyID, warrantyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetWarrantyPartsByWarrantyIDRow{}
	for rows.Next() {
		var i GetWarrantyPartsByWarrantyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.WarrantyID,
			&i.ProductAllocationID,
			&i.CarPartID,
			&i.InstallationImageUrl,
			&i.ApprovalStatus,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CarPartName,
			&i.CarPartCode,
			&i.FilmSerialNumber,
			&i.WarrantyInMonths,
			&i.ProductBrand,
			&i.ProductType,
			&i.ProductSeries,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarranties = `-- name: ListWarranties :many
SELECT
    w.id, w.shop_id, w.client_name, w.client_contact, w.client_email, w.car_brand, w.car_model, w.car_colour, w.car_plate_no, w.car_chassis_no, w.installation_date, w.reference_no, w.warranty_no, w.invoice_attachment_url, w.is_active, w.approval_status, w.remarks, w.created_at, w.updated_at,
    s.shop_name,
    s.branch_code
FROM warranties w
JOIN shops s ON w.shop_id = s.id
ORDER BY w.created_at DESC
`

type ListWarrantiesRow struct {
	ID                   int32                  `db:"id" json:"id"`
	ShopID               int32                  `db:"shop_id" json:"shopId"`
	ClientName           string                 `db:"client_name" json:"clientName"`
	ClientContact        string                 `db:"client_contact" json:"clientContact"`
	ClientEmail          string                 `db:"client_email" json:"clientEmail"`
	CarBrand             string                 `db:"car_brand" json:"carBrand"`
	CarModel             string                 `db:"car_model" json:"carModel"`
	CarColour            string                 `db:"car_colour" json:"carColour"`
	CarPlateNo           string                 `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo         string                 `db:"car_chassis_no" json:"carChassisNo"`
	InstallationDate     time.Time              `db:"installation_date" json:"installationDate"`
	ReferenceNo          *string                `db:"reference_no" json:"referenceNo"`
	WarrantyNo           string                 `db:"warranty_no" json:"warrantyNo"`
	InvoiceAttachmentUrl string                 `db:"invoice_attachment_url" json:"invoiceAttachmentUrl"`
	IsActive             bool                   `db:"is_active" json:"isActive"`
	ApprovalStatus       WarrantyApprovalStatus `db:"approval_status" json:"approvalStatus"`
	Remarks              *string                `db:"remarks" json:"remarks"`
	CreatedAt            time.Time              `db:"created_at" json:"createdAt"`
	UpdatedAt            time.Time              `db:"updated_at" json:"updatedAt"`
	ShopName             string                 `db:"shop_name" json:"shopName"`
	BranchCode           string                 `db:"branch_code" json:"branchCode"`
}

func (q *Queries) ListWarranties(ctx context.Context) ([]*ListWarrantiesRow, error) {
	rows, err := q.db.Query(ctx, listWarranties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListWarrantiesRow{}
	for rows.Next() {
		var i ListWarrantiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ClientName,
			&i.ClientContact,
			&i.ClientEmail,
			&i.CarBrand,
			&i.CarModel,
			&i.CarColour,
			&i.CarPlateNo,
			&i.CarChassisNo,
			&i.InstallationDate,
			&i.ReferenceNo,
			&i.WarrantyNo,
			&i.InvoiceAttachmentUrl,
			&i.IsActive,
			&i.ApprovalStatus,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShopName,
			&i.BranchCode,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarranty = `-- name: UpdateWarranty :one
UPDATE warranties
SET
    shop_id = $2,
    client_name = $3,
    client_contact = $4,
    client_email = $5,
    car_brand = $6,
    car_model = $7,
    car_colour = $8,
    car_plate_no = $9,
    car_chassis_no = $10,
    installation_date = $11,
    reference_no = $12,
    warranty_no = $13,
    invoice_attachment_url = $14,
    remarks = $15,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, approval_status, remarks, created_at, updated_at
`

type UpdateWarrantyParams struct {
	ID                   int32     `db:"id" json:"id"`
	ShopID               int32     `db:"shop_id" json:"shopId"`
	ClientName           string    `db:"client_name" json:"clientName"`
	ClientContact        string    `db:"client_contact" json:"clientContact"`
	ClientEmail          string    `db:"client_email" json:"clientEmail"`
	CarBrand             string    `db:"car_brand" json:"carBrand"`
	CarModel             string    `db:"car_model" json:"carModel"`
	CarColour            string    `db:"car_colour" json:"carColour"`
	CarPlateNo           string    `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo         string    `db:"car_chassis_no" json:"carChassisNo"`
	InstallationDate     time.Time `db:"installation_date" json:"installationDate"`
	ReferenceNo          *string   `db:"reference_no" json:"referenceNo"`
	WarrantyNo           string    `db:"warranty_no" json:"warrantyNo"`
	InvoiceAttachmentUrl string    `db:"invoice_attachment_url" json:"invoiceAttachmentUrl"`
	Remarks              *string   `db:"remarks" json:"remarks"`
}

func (q *Queries) UpdateWarranty(ctx context.Context, arg *UpdateWarrantyParams) (*Warranty, error) {
	row := q.db.QueryRow(ctx, updateWarranty,
		arg.ID,
		arg.ShopID,
		arg.ClientName,
		arg.ClientContact,
		arg.ClientEmail,
		arg.CarBrand,
		arg.CarModel,
		arg.CarColour,
		arg.CarPlateNo,
		arg.CarChassisNo,
		arg.InstallationDate,
		arg.ReferenceNo,
		arg.WarrantyNo,
		arg.InvoiceAttachmentUrl,
		arg.Remarks,
	)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ClientName,
		&i.ClientContact,
		&i.ClientEmail,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColour,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.InvoiceAttachmentUrl,
		&i.IsActive,
		&i.ApprovalStatus,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateWarrantyApproval = `-- name: UpdateWarrantyApproval :one
UPDATE warranties
SET
    approval_status = $2,
    remarks = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url, is_active, approval_status, remarks, created_at, updated_at
`

type UpdateWarrantyApprovalParams struct {
	ID             int32                  `db:"id" json:"id"`
	ApprovalStatus WarrantyApprovalStatus `db:"approval_status" json:"approvalStatus"`
	Remarks        *string                `db:"remarks" json:"remarks"`
}

func (q *Queries) UpdateWarrantyApproval(ctx context.Context, arg *UpdateWarrantyApprovalParams) (*Warranty, error) {
	row := q.db.QueryRow(ctx, updateWarrantyApproval, arg.ID, arg.ApprovalStatus, arg.Remarks)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ClientName,
		&i.ClientContact,
		&i.ClientEmail,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColour,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.InvoiceAttachmentUrl,
		&i.IsActive,
		&i.ApprovalStatus,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateWarrantyPart = `-- name: UpdateWarrantyPart :one
UPDATE warranty_parts
SET
    warranty_id = $2,
    car_part_id = $3,
    product_allocation_id = $4,
    installation_image_url = $5,
    remarks = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, warranty_id, product_allocation_id, car_part_id, installation_image_url, approval_status, remarks, created_at, updated_at
`

type UpdateWarrantyPartParams struct {
	ID                   int32   `db:"id" json:"id"`
	WarrantyID           int32   `db:"warranty_id" json:"warrantyId"`
	CarPartID            int32   `db:"car_part_id" json:"carPartId"`
	ProductAllocationID  int32   `db:"product_allocation_id" json:"productAllocationId"`
	InstallationImageUrl string  `db:"installation_image_url" json:"installationImageUrl"`
	Remarks              *string `db:"remarks" json:"remarks"`
}

func (q *Queries) UpdateWarrantyPart(ctx context.Context, arg *UpdateWarrantyPartParams) (*WarrantyPart, error) {
	row := q.db.QueryRow(ctx, updateWarrantyPart,
		arg.ID,
		arg.WarrantyID,
		arg.CarPartID,
		arg.ProductAllocationID,
		arg.InstallationImageUrl,
		arg.Remarks,
	)
	var i WarrantyPart
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ProductAllocationID,
		&i.CarPartID,
		&i.InstallationImageUrl,
		&i.ApprovalStatus,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateWarrantyPartApproval = `-- name: UpdateWarrantyPartApproval :one
UPDATE warranty_parts
SET
    approval_status = $2,
    remarks = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, warranty_id, product_allocation_id, car_part_id, installation_image_url, approval_status, remarks, created_at, updated_at
`

type UpdateWarrantyPartApprovalParams struct {
	ID             int32                  `db:"id" json:"id"`
	ApprovalStatus WarrantyApprovalStatus `db:"approval_status" json:"approvalStatus"`
	Remarks        *string                `db:"remarks" json:"remarks"`
}

func (q *Queries) UpdateWarrantyPartApproval(ctx context.Context, arg *UpdateWarrantyPartApprovalParams) (*WarrantyPart, error) {
	row := q.db.QueryRow(ctx, updateWarrantyPartApproval, arg.ID, arg.ApprovalStatus, arg.Remarks)
	var i WarrantyPart
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ProductAllocationID,
		&i.CarPartID,
		&i.InstallationImageUrl,
		&i.ApprovalStatus,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
