// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warranty_queries.sql

package warranties

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCarPart = `-- name: CreateCarPart :one
INSERT INTO car_parts (part_name, description)
VALUES ($1, $2)
RETURNING id, part_name, description, is_active, created_at, updated_at
`

type CreateCarPartParams struct {
	PartName    string      `db:"part_name" json:"partName"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) CreateCarPart(ctx context.Context, arg *CreateCarPartParams) (*CarPart, error) {
	row := q.db.QueryRow(ctx, createCarPart, arg.PartName, arg.Description)
	var i CarPart
	err := row.Scan(
		&i.ID,
		&i.PartName,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createWarranty = `-- name: CreateWarranty :one
INSERT INTO warranties (
    customer_name, customer_email, customer_contact,
    car_brand, car_model, car_color, car_plate_no, car_chassis_no,
    shop_allocations_id, car_parts_id, image_url,
    installation_date, reference_no, warranty_no
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14
)
RETURNING id, customer_name, customer_email, customer_contact, car_brand, car_model, car_color, car_plate_no, car_chassis_no, shop_allocations_id, car_parts_id, image_url, installation_date, reference_no, warranty_no, created_at, updated_at
`

type CreateWarrantyParams struct {
	CustomerName      string      `db:"customer_name" json:"customerName"`
	CustomerEmail     string      `db:"customer_email" json:"customerEmail"`
	CustomerContact   string      `db:"customer_contact" json:"customerContact"`
	CarBrand          string      `db:"car_brand" json:"carBrand"`
	CarModel          string      `db:"car_model" json:"carModel"`
	CarColor          string      `db:"car_color" json:"carColor"`
	CarPlateNo        string      `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo      string      `db:"car_chassis_no" json:"carChassisNo"`
	ShopAllocationsID uuid.UUID   `db:"shop_allocations_id" json:"shopAllocationsId"`
	CarPartsID        uuid.UUID   `db:"car_parts_id" json:"carPartsId"`
	ImageUrl          string      `db:"image_url" json:"imageUrl"`
	InstallationDate  pgtype.Date `db:"installation_date" json:"installationDate"`
	ReferenceNo       string      `db:"reference_no" json:"referenceNo"`
	WarrantyNo        string      `db:"warranty_no" json:"warrantyNo"`
}

func (q *Queries) CreateWarranty(ctx context.Context, arg *CreateWarrantyParams) (*Warranty, error) {
	row := q.db.QueryRow(ctx, createWarranty,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerContact,
		arg.CarBrand,
		arg.CarModel,
		arg.CarColor,
		arg.CarPlateNo,
		arg.CarChassisNo,
		arg.ShopAllocationsID,
		arg.CarPartsID,
		arg.ImageUrl,
		arg.InstallationDate,
		arg.ReferenceNo,
		arg.WarrantyNo,
	)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerContact,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColor,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.ShopAllocationsID,
		&i.CarPartsID,
		&i.ImageUrl,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteCarPart = `-- name: DeleteCarPart :exec
DELETE FROM car_parts
WHERE id = $1
`

func (q *Queries) DeleteCarPart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCarPart, id)
	return err
}

const deleteWarranty = `-- name: DeleteWarranty :exec
DELETE FROM warranties
WHERE id = $1
`

func (q *Queries) DeleteWarranty(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWarranty, id)
	return err
}

const getCarPartByID = `-- name: GetCarPartByID :one
SELECT id, part_name, description, is_active, created_at, updated_at FROM car_parts
WHERE id = $1
`

func (q *Queries) GetCarPartByID(ctx context.Context, id uuid.UUID) (*CarPart, error) {
	row := q.db.QueryRow(ctx, getCarPartByID, id)
	var i CarPart
	err := row.Scan(
		&i.ID,
		&i.PartName,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWarrantyByID = `-- name: GetWarrantyByID :one
SELECT id, customer_name, customer_email, customer_contact, car_brand, car_model, car_color, car_plate_no, car_chassis_no, shop_allocations_id, car_parts_id, image_url, installation_date, reference_no, warranty_no, created_at, updated_at FROM warranties
WHERE id = $1
`

func (q *Queries) GetWarrantyByID(ctx context.Context, id uuid.UUID) (*Warranty, error) {
	row := q.db.QueryRow(ctx, getWarrantyByID, id)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerContact,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColor,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.ShopAllocationsID,
		&i.CarPartsID,
		&i.ImageUrl,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listCarParts = `-- name: ListCarParts :many
SELECT id, part_name, description, is_active, created_at, updated_at FROM car_parts
ORDER BY created_at DESC
`

func (q *Queries) ListCarParts(ctx context.Context) ([]*CarPart, error) {
	rows, err := q.db.Query(ctx, listCarParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CarPart{}
	for rows.Next() {
		var i CarPart
		if err := rows.Scan(
			&i.ID,
			&i.PartName,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarranties = `-- name: ListWarranties :many
SELECT id, customer_name, customer_email, customer_contact, car_brand, car_model, car_color, car_plate_no, car_chassis_no, shop_allocations_id, car_parts_id, image_url, installation_date, reference_no, warranty_no, created_at, updated_at FROM warranties
ORDER BY installation_date DESC
`

func (q *Queries) ListWarranties(ctx context.Context) ([]*Warranty, error) {
	rows, err := q.db.Query(ctx, listWarranties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerContact,
			&i.CarBrand,
			&i.CarModel,
			&i.CarColor,
			&i.CarPlateNo,
			&i.CarChassisNo,
			&i.ShopAllocationsID,
			&i.CarPartsID,
			&i.ImageUrl,
			&i.InstallationDate,
			&i.ReferenceNo,
			&i.WarrantyNo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCarPart = `-- name: UpdateCarPart :one
UPDATE car_parts
SET part_name = $1, description = $2
WHERE id = $3
RETURNING id, part_name, description, is_active, created_at, updated_at
`

type UpdateCarPartParams struct {
	PartName    string      `db:"part_name" json:"partName"`
	Description pgtype.Text `db:"description" json:"description"`
	ID          uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateCarPart(ctx context.Context, arg *UpdateCarPartParams) (*CarPart, error) {
	row := q.db.QueryRow(ctx, updateCarPart, arg.PartName, arg.Description, arg.ID)
	var i CarPart
	err := row.Scan(
		&i.ID,
		&i.PartName,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateWarranty = `-- name: UpdateWarranty :one
UPDATE warranties
SET customer_name = $1, customer_email = $2, customer_contact = $3,
    car_brand = $4, car_model = $5, car_color = $6, car_plate_no = $7, car_chassis_no = $8,
    shop_allocations_id = $9, car_parts_id = $10, image_url = $11,
    installation_date = $12, reference_no = $13, warranty_no = $14
WHERE id = $15
RETURNING id, customer_name, customer_email, customer_contact, car_brand, car_model, car_color, car_plate_no, car_chassis_no, shop_allocations_id, car_parts_id, image_url, installation_date, reference_no, warranty_no, created_at, updated_at
`

type UpdateWarrantyParams struct {
	CustomerName      string      `db:"customer_name" json:"customerName"`
	CustomerEmail     string      `db:"customer_email" json:"customerEmail"`
	CustomerContact   string      `db:"customer_contact" json:"customerContact"`
	CarBrand          string      `db:"car_brand" json:"carBrand"`
	CarModel          string      `db:"car_model" json:"carModel"`
	CarColor          string      `db:"car_color" json:"carColor"`
	CarPlateNo        string      `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo      string      `db:"car_chassis_no" json:"carChassisNo"`
	ShopAllocationsID uuid.UUID   `db:"shop_allocations_id" json:"shopAllocationsId"`
	CarPartsID        uuid.UUID   `db:"car_parts_id" json:"carPartsId"`
	ImageUrl          string      `db:"image_url" json:"imageUrl"`
	InstallationDate  pgtype.Date `db:"installation_date" json:"installationDate"`
	ReferenceNo       string      `db:"reference_no" json:"referenceNo"`
	WarrantyNo        string      `db:"warranty_no" json:"warrantyNo"`
	ID                uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateWarranty(ctx context.Context, arg *UpdateWarrantyParams) (*Warranty, error) {
	row := q.db.QueryRow(ctx, updateWarranty,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerContact,
		arg.CarBrand,
		arg.CarModel,
		arg.CarColor,
		arg.CarPlateNo,
		arg.CarChassisNo,
		arg.ShopAllocationsID,
		arg.CarPartsID,
		arg.ImageUrl,
		arg.InstallationDate,
		arg.ReferenceNo,
		arg.WarrantyNo,
		arg.ID,
	)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerContact,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColor,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.ShopAllocationsID,
		&i.CarPartsID,
		&i.ImageUrl,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
