// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package shops

import (
	"time"
)

type MsiaState struct {
	ID        int32     `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Code      string    `db:"code" json:"code"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time `db:"updated_at" json:"updatedAt"`
}

type Product struct {
	ID               int32     `db:"id" json:"id"`
	BrandID          int32     `db:"brand_id" json:"brandId"`
	TypeID           int32     `db:"type_id" json:"typeId"`
	SeriesID         int32     `db:"series_id" json:"seriesId"`
	NameID           int32     `db:"name_id" json:"nameId"`
	WarrantyInMonths int32     `db:"warranty_in_months" json:"warrantyInMonths"`
	FilmSerialNumber string    `db:"film_serial_number" json:"filmSerialNumber"`
	FilmQuantity     int32     `db:"film_quantity" json:"filmQuantity"`
	ShipmentNumber   string    `db:"shipment_number" json:"shipmentNumber"`
	Description      string    `db:"description" json:"description"`
	IsActive         bool      `db:"is_active" json:"isActive"`
	CreatedAt        time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt        time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductAllocation struct {
	ID             int32     `db:"id" json:"id"`
	ProductID      int32     `db:"product_id" json:"productId"`
	ShopID         int32     `db:"shop_id" json:"shopId"`
	FilmQuantity   int32     `db:"film_quantity" json:"filmQuantity"`
	AllocationDate time.Time `db:"allocation_date" json:"allocationDate"`
	CreatedAt      time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt      time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductAllocationsView struct {
	AllocationID     int32     `db:"allocation_id" json:"allocationId"`
	FilmSerialNumber string    `db:"film_serial_number" json:"filmSerialNumber"`
	ProductName      string    `db:"product_name" json:"productName"`
	ShopName         string    `db:"shop_name" json:"shopName"`
	BranchCode       string    `db:"branch_code" json:"branchCode"`
	FilmQuantity     int32     `db:"film_quantity" json:"filmQuantity"`
	AllocationDate   time.Time `db:"allocation_date" json:"allocationDate"`
	CreatedAt        time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt        time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductBrand struct {
	ID          int32     `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductName struct {
	ID          int32     `db:"id" json:"id"`
	SeriesID    int32     `db:"series_id" json:"seriesId"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductSeries struct {
	ID          int32     `db:"id" json:"id"`
	TypeID      int32     `db:"type_id" json:"typeId"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductType struct {
	ID          int32     `db:"id" json:"id"`
	BrandID     int32     `db:"brand_id" json:"brandId"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductsView struct {
	ProductID        int32     `db:"product_id" json:"productId"`
	BrandName        string    `db:"brand_name" json:"brandName"`
	TypeName         string    `db:"type_name" json:"typeName"`
	SeriesName       string    `db:"series_name" json:"seriesName"`
	ProductName      string    `db:"product_name" json:"productName"`
	WarrantyPeriod   int32     `db:"warranty_period" json:"warrantyPeriod"`
	FilmSerialNumber string    `db:"film_serial_number" json:"filmSerialNumber"`
	FilmQuantity     int32     `db:"film_quantity" json:"filmQuantity"`
	ShipmentNumber   string    `db:"shipment_number" json:"shipmentNumber"`
	Description      string    `db:"description" json:"description"`
	IsActive         bool      `db:"is_active" json:"isActive"`
	CreatedAt        time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt        time.Time `db:"updated_at" json:"updatedAt"`
}

type Shop struct {
	ID                        int32     `db:"id" json:"id"`
	CompanyName               string    `db:"company_name" json:"companyName"`
	CompanyRegistrationNumber string    `db:"company_registration_number" json:"companyRegistrationNumber"`
	CompanyLicenseImageUrl    string    `db:"company_license_image_url" json:"companyLicenseImageUrl"`
	CompanyContactNumber      string    `db:"company_contact_number" json:"companyContactNumber"`
	CompanyEmail              string    `db:"company_email" json:"companyEmail"`
	CompanyWebsiteUrl         string    `db:"company_website_url" json:"companyWebsiteUrl"`
	ShopName                  string    `db:"shop_name" json:"shopName"`
	ShopAddress               string    `db:"shop_address" json:"shopAddress"`
	MsiaStateID               *int32    `db:"msia_state_id" json:"msiaStateId"`
	BranchCode                string    `db:"branch_code" json:"branchCode"`
	ShopImageUrl              string    `db:"shop_image_url" json:"shopImageUrl"`
	PicName                   string    `db:"pic_name" json:"picName"`
	PicPosition               string    `db:"pic_position" json:"picPosition"`
	PicContactNumber          string    `db:"pic_contact_number" json:"picContactNumber"`
	PicEmail                  string    `db:"pic_email" json:"picEmail"`
	LoginUsername             string    `db:"login_username" json:"loginUsername"`
	LoginPasswordHash         string    `db:"login_password_hash" json:"loginPasswordHash"`
	IsActive                  bool      `db:"is_active" json:"isActive"`
	CreatedAt                 time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt                 time.Time `db:"updated_at" json:"updatedAt"`
}

type ShopsView struct {
	ShopID                    int32     `db:"shop_id" json:"shopId"`
	CompanyName               string    `db:"company_name" json:"companyName"`
	CompanyRegistrationNumber string    `db:"company_registration_number" json:"companyRegistrationNumber"`
	CompanyContactNumber      string    `db:"company_contact_number" json:"companyContactNumber"`
	CompanyEmail              string    `db:"company_email" json:"companyEmail"`
	CompanyWebsiteUrl         string    `db:"company_website_url" json:"companyWebsiteUrl"`
	ShopName                  string    `db:"shop_name" json:"shopName"`
	ShopAddress               string    `db:"shop_address" json:"shopAddress"`
	MsiaStateName             *string   `db:"msia_state_name" json:"msiaStateName"`
	BranchCode                string    `db:"branch_code" json:"branchCode"`
	ShopImageUrl              string    `db:"shop_image_url" json:"shopImageUrl"`
	PicName                   string    `db:"pic_name" json:"picName"`
	PicPosition               string    `db:"pic_position" json:"picPosition"`
	PicContactNumber          string    `db:"pic_contact_number" json:"picContactNumber"`
	PicEmail                  string    `db:"pic_email" json:"picEmail"`
	LoginUsername             string    `db:"login_username" json:"loginUsername"`
	IsActive                  bool      `db:"is_active" json:"isActive"`
	CreatedAt                 time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt                 time.Time `db:"updated_at" json:"updatedAt"`
}

type WarrantyPeriod struct {
	ID          int32     `db:"id" json:"id"`
	PeriodYears int32     `db:"period_years" json:"periodYears"`
	Description string    `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time `db:"updated_at" json:"updatedAt"`
}
