// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package shops

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProductAllocation(ctx context.Context, arg *CreateProductAllocationParams) (*ProductAllocation, error)
	CreateShop(ctx context.Context, arg *CreateShopParams) (*Shop, error)
	CreateState(ctx context.Context, name string) (*State, error)
	DeleteProductAllocation(ctx context.Context, id uuid.UUID) error
	DeleteShop(ctx context.Context, id uuid.UUID) error
	DeleteState(ctx context.Context, id uuid.UUID) error
	GetProductAllocationByID(ctx context.Context, id uuid.UUID) (*ProductAllocation, error)
	GetShopByID(ctx context.Context, id uuid.UUID) (*Shop, error)
	GetShopDetailsByID(ctx context.Context, shopID uuid.UUID) (*ShopDetail, error)
	GetStateByID(ctx context.Context, id uuid.UUID) (*State, error)
	ListProductAllocations(ctx context.Context) ([]*ProductAllocation, error)
	ListShopDetails(ctx context.Context) ([]*ShopDetail, error)
	ListShops(ctx context.Context) ([]*Shop, error)
	ListStates(ctx context.Context) ([]*State, error)
	UpdateProductAllocation(ctx context.Context, arg *UpdateProductAllocationParams) (*ProductAllocation, error)
	UpdateShop(ctx context.Context, arg *UpdateShopParams) (*Shop, error)
	UpdateState(ctx context.Context, arg *UpdateStateParams) (*State, error)
}

var _ Querier = (*Queries)(nil)
