// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package shops

import (
	"context"
)

type Querier interface {
	CreateShop(ctx context.Context, arg *CreateShopParams) (*Shop, error)
	GetMaxBranchCodeByStateCode(ctx context.Context, code string) (string, error)
	GetMsiaStateByID(ctx context.Context, id int32) (*MsiaState, error)
	GetShopByID(ctx context.Context, id int32) (*Shop, error)
	GetShops(ctx context.Context) ([]*GetShopsRow, error)
	ListMsiaStates(ctx context.Context) ([]*MsiaState, error)
	UpdateShop(ctx context.Context, arg *UpdateShopParams) (*Shop, error)
}

var _ Querier = (*Queries)(nil)
