// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shop_queries.sql

package shops

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProductAllocation = `-- name: CreateProductAllocation :one
INSERT INTO product_allocations (product_id, shop_id, film_quantity)
VALUES ($1, $2, $3)
RETURNING id, product_id, shop_id, film_quantity, allocated_date, created_at, updated_at
`

type CreateProductAllocationParams struct {
	ProductID    uuid.UUID `db:"product_id" json:"productId"`
	ShopID       uuid.UUID `db:"shop_id" json:"shopId"`
	FilmQuantity int32     `db:"film_quantity" json:"filmQuantity"`
}

func (q *Queries) CreateProductAllocation(ctx context.Context, arg *CreateProductAllocationParams) (*ProductAllocation, error) {
	row := q.db.QueryRow(ctx, createProductAllocation, arg.ProductID, arg.ShopID, arg.FilmQuantity)
	var i ProductAllocation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ShopID,
		&i.FilmQuantity,
		&i.AllocatedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createShop = `-- name: CreateShop :one
INSERT INTO shops (
    state_id, company_name, company_registration_no, company_license_image_url,
    company_email, company_contact, company_website, name, type, address,
    image_url, pic_name, pic_contact, pic_email, pic_position,
    username, login_hash_password, is_active
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18
)
RETURNING id, state_id, company_name, company_registration_no, company_license_image_url, company_email, company_contact, company_website, name, type, address, image_url, pic_name, pic_contact, pic_email, pic_position, username, login_hash_password, is_active, created_at, updated_at
`

type CreateShopParams struct {
	StateID                uuid.UUID   `db:"state_id" json:"stateId"`
	CompanyName            string      `db:"company_name" json:"companyName"`
	CompanyRegistrationNo  string      `db:"company_registration_no" json:"companyRegistrationNo"`
	CompanyLicenseImageUrl string      `db:"company_license_image_url" json:"companyLicenseImageUrl"`
	CompanyEmail           string      `db:"company_email" json:"companyEmail"`
	CompanyContact         string      `db:"company_contact" json:"companyContact"`
	CompanyWebsite         pgtype.Text `db:"company_website" json:"companyWebsite"`
	Name                   string      `db:"name" json:"name"`
	Type                   string      `db:"type" json:"type"`
	Address                string      `db:"address" json:"address"`
	ImageUrl               string      `db:"image_url" json:"imageUrl"`
	PicName                string      `db:"pic_name" json:"picName"`
	PicContact             string      `db:"pic_contact" json:"picContact"`
	PicEmail               string      `db:"pic_email" json:"picEmail"`
	PicPosition            string      `db:"pic_position" json:"picPosition"`
	Username               string      `db:"username" json:"username"`
	LoginHashPassword      string      `db:"login_hash_password" json:"loginHashPassword"`
	IsActive               pgtype.Bool `db:"is_active" json:"isActive"`
}

func (q *Queries) CreateShop(ctx context.Context, arg *CreateShopParams) (*Shop, error) {
	row := q.db.QueryRow(ctx, createShop,
		arg.StateID,
		arg.CompanyName,
		arg.CompanyRegistrationNo,
		arg.CompanyLicenseImageUrl,
		arg.CompanyEmail,
		arg.CompanyContact,
		arg.CompanyWebsite,
		arg.Name,
		arg.Type,
		arg.Address,
		arg.ImageUrl,
		arg.PicName,
		arg.PicContact,
		arg.PicEmail,
		arg.PicPosition,
		arg.Username,
		arg.LoginHashPassword,
		arg.IsActive,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.StateID,
		&i.CompanyName,
		&i.CompanyRegistrationNo,
		&i.CompanyLicenseImageUrl,
		&i.CompanyEmail,
		&i.CompanyContact,
		&i.CompanyWebsite,
		&i.Name,
		&i.Type,
		&i.Address,
		&i.ImageUrl,
		&i.PicName,
		&i.PicContact,
		&i.PicEmail,
		&i.PicPosition,
		&i.Username,
		&i.LoginHashPassword,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createState = `-- name: CreateState :one
INSERT INTO states (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateState(ctx context.Context, name string) (*State, error) {
	row := q.db.QueryRow(ctx, createState, name)
	var i State
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteProductAllocation = `-- name: DeleteProductAllocation :exec
DELETE FROM product_allocations
WHERE id = $1
`

func (q *Queries) DeleteProductAllocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductAllocation, id)
	return err
}

const deleteShop = `-- name: DeleteShop :exec
DELETE FROM shops
WHERE id = $1
`

func (q *Queries) DeleteShop(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShop, id)
	return err
}

const deleteState = `-- name: DeleteState :exec
DELETE FROM states
WHERE id = $1
`

func (q *Queries) DeleteState(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteState, id)
	return err
}

const getProductAllocationByID = `-- name: GetProductAllocationByID :one
SELECT id, product_id, shop_id, film_quantity, allocated_date, created_at, updated_at FROM product_allocations
WHERE id = $1
`

func (q *Queries) GetProductAllocationByID(ctx context.Context, id uuid.UUID) (*ProductAllocation, error) {
	row := q.db.QueryRow(ctx, getProductAllocationByID, id)
	var i ProductAllocation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ShopID,
		&i.FilmQuantity,
		&i.AllocatedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, state_id, company_name, company_registration_no, company_license_image_url, company_email, company_contact, company_website, name, type, address, image_url, pic_name, pic_contact, pic_email, pic_position, username, login_hash_password, is_active, created_at, updated_at FROM shops
WHERE id = $1
`

func (q *Queries) GetShopByID(ctx context.Context, id uuid.UUID) (*Shop, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.StateID,
		&i.CompanyName,
		&i.CompanyRegistrationNo,
		&i.CompanyLicenseImageUrl,
		&i.CompanyEmail,
		&i.CompanyContact,
		&i.CompanyWebsite,
		&i.Name,
		&i.Type,
		&i.Address,
		&i.ImageUrl,
		&i.PicName,
		&i.PicContact,
		&i.PicEmail,
		&i.PicPosition,
		&i.Username,
		&i.LoginHashPassword,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getShopDetailsByID = `-- name: GetShopDetailsByID :one
SELECT shop_id, company_name, company_registration_no, company_license_image_url, company_email, company_contact, company_website, name, type, address, image_url, pic_name, pic_contact, pic_email, pic_position, login_hash_password, is_active, created_at, updated_at, state_id, state_name FROM shop_details
WHERE shop_id = $1
`

func (q *Queries) GetShopDetailsByID(ctx context.Context, shopID uuid.UUID) (*ShopDetail, error) {
	row := q.db.QueryRow(ctx, getShopDetailsByID, shopID)
	var i ShopDetail
	err := row.Scan(
		&i.ShopID,
		&i.CompanyName,
		&i.CompanyRegistrationNo,
		&i.CompanyLicenseImageUrl,
		&i.CompanyEmail,
		&i.CompanyContact,
		&i.CompanyWebsite,
		&i.Name,
		&i.Type,
		&i.Address,
		&i.ImageUrl,
		&i.PicName,
		&i.PicContact,
		&i.PicEmail,
		&i.PicPosition,
		&i.LoginHashPassword,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateID,
		&i.StateName,
	)
	return &i, err
}

const getStateByID = `-- name: GetStateByID :one
SELECT id, name, created_at, updated_at FROM states
WHERE id = $1
`

func (q *Queries) GetStateByID(ctx context.Context, id uuid.UUID) (*State, error) {
	row := q.db.QueryRow(ctx, getStateByID, id)
	var i State
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listProductAllocations = `-- name: ListProductAllocations :many
SELECT id, product_id, shop_id, film_quantity, allocated_date, created_at, updated_at FROM product_allocations
ORDER BY allocated_date DESC
`

func (q *Queries) ListProductAllocations(ctx context.Context) ([]*ProductAllocation, error) {
	rows, err := q.db.Query(ctx, listProductAllocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProductAllocation{}
	for rows.Next() {
		var i ProductAllocation
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ShopID,
			&i.FilmQuantity,
			&i.AllocatedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopDetails = `-- name: ListShopDetails :many
SELECT shop_id, company_name, company_registration_no, company_license_image_url, company_email, company_contact, company_website, name, type, address, image_url, pic_name, pic_contact, pic_email, pic_position, login_hash_password, is_active, created_at, updated_at, state_id, state_name FROM shop_details
`

func (q *Queries) ListShopDetails(ctx context.Context) ([]*ShopDetail, error) {
	rows, err := q.db.Query(ctx, listShopDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ShopDetail{}
	for rows.Next() {
		var i ShopDetail
		if err := rows.Scan(
			&i.ShopID,
			&i.CompanyName,
			&i.CompanyRegistrationNo,
			&i.CompanyLicenseImageUrl,
			&i.CompanyEmail,
			&i.CompanyContact,
			&i.CompanyWebsite,
			&i.Name,
			&i.Type,
			&i.Address,
			&i.ImageUrl,
			&i.PicName,
			&i.PicContact,
			&i.PicEmail,
			&i.PicPosition,
			&i.LoginHashPassword,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateID,
			&i.StateName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShops = `-- name: ListShops :many
SELECT id, state_id, company_name, company_registration_no, company_license_image_url, company_email, company_contact, company_website, name, type, address, image_url, pic_name, pic_contact, pic_email, pic_position, username, login_hash_password, is_active, created_at, updated_at FROM shops
ORDER BY created_at DESC
`

func (q *Queries) ListShops(ctx context.Context) ([]*Shop, error) {
	rows, err := q.db.Query(ctx, listShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Shop{}
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.StateID,
			&i.CompanyName,
			&i.CompanyRegistrationNo,
			&i.CompanyLicenseImageUrl,
			&i.CompanyEmail,
			&i.CompanyContact,
			&i.CompanyWebsite,
			&i.Name,
			&i.Type,
			&i.Address,
			&i.ImageUrl,
			&i.PicName,
			&i.PicContact,
			&i.PicEmail,
			&i.PicPosition,
			&i.Username,
			&i.LoginHashPassword,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStates = `-- name: ListStates :many
SELECT id, name, created_at, updated_at FROM states
ORDER BY name ASC
`

func (q *Queries) ListStates(ctx context.Context) ([]*State, error) {
	rows, err := q.db.Query(ctx, listStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*State{}
	for rows.Next() {
		var i State
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductAllocation = `-- name: UpdateProductAllocation :one
UPDATE product_allocations
SET product_id = $1, shop_id = $2, film_quantity = $3
WHERE id = $4
RETURNING id, product_id, shop_id, film_quantity, allocated_date, created_at, updated_at
`

type UpdateProductAllocationParams struct {
	ProductID    uuid.UUID `db:"product_id" json:"productId"`
	ShopID       uuid.UUID `db:"shop_id" json:"shopId"`
	FilmQuantity int32     `db:"film_quantity" json:"filmQuantity"`
	ID           uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateProductAllocation(ctx context.Context, arg *UpdateProductAllocationParams) (*ProductAllocation, error) {
	row := q.db.QueryRow(ctx, updateProductAllocation,
		arg.ProductID,
		arg.ShopID,
		arg.FilmQuantity,
		arg.ID,
	)
	var i ProductAllocation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ShopID,
		&i.FilmQuantity,
		&i.AllocatedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateShop = `-- name: UpdateShop :one
UPDATE shops
SET
    state_id = $1,
    company_name = $2,
    company_registration_no = $3,
    company_license_image_url = $4,
    company_email = $5,
    company_contact = $6,
    company_website = $7,
    name = $8,
    type = $9,
    address = $10,
    image_url = $11,
    pic_name = $12,
    pic_contact = $13,
    pic_email = $14,
    pic_position = $15,
    login_hash_password = $16,
    is_active = $17
WHERE id = $18
RETURNING id, state_id, company_name, company_registration_no, company_license_image_url, company_email, company_contact, company_website, name, type, address, image_url, pic_name, pic_contact, pic_email, pic_position, username, login_hash_password, is_active, created_at, updated_at
`

type UpdateShopParams struct {
	StateID                uuid.UUID   `db:"state_id" json:"stateId"`
	CompanyName            string      `db:"company_name" json:"companyName"`
	CompanyRegistrationNo  string      `db:"company_registration_no" json:"companyRegistrationNo"`
	CompanyLicenseImageUrl string      `db:"company_license_image_url" json:"companyLicenseImageUrl"`
	CompanyEmail           string      `db:"company_email" json:"companyEmail"`
	CompanyContact         string      `db:"company_contact" json:"companyContact"`
	CompanyWebsite         pgtype.Text `db:"company_website" json:"companyWebsite"`
	Name                   string      `db:"name" json:"name"`
	Type                   string      `db:"type" json:"type"`
	Address                string      `db:"address" json:"address"`
	ImageUrl               string      `db:"image_url" json:"imageUrl"`
	PicName                string      `db:"pic_name" json:"picName"`
	PicContact             string      `db:"pic_contact" json:"picContact"`
	PicEmail               string      `db:"pic_email" json:"picEmail"`
	PicPosition            string      `db:"pic_position" json:"picPosition"`
	LoginHashPassword      string      `db:"login_hash_password" json:"loginHashPassword"`
	IsActive               pgtype.Bool `db:"is_active" json:"isActive"`
	ID                     uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateShop(ctx context.Context, arg *UpdateShopParams) (*Shop, error) {
	row := q.db.QueryRow(ctx, updateShop,
		arg.StateID,
		arg.CompanyName,
		arg.CompanyRegistrationNo,
		arg.CompanyLicenseImageUrl,
		arg.CompanyEmail,
		arg.CompanyContact,
		arg.CompanyWebsite,
		arg.Name,
		arg.Type,
		arg.Address,
		arg.ImageUrl,
		arg.PicName,
		arg.PicContact,
		arg.PicEmail,
		arg.PicPosition,
		arg.LoginHashPassword,
		arg.IsActive,
		arg.ID,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.StateID,
		&i.CompanyName,
		&i.CompanyRegistrationNo,
		&i.CompanyLicenseImageUrl,
		&i.CompanyEmail,
		&i.CompanyContact,
		&i.CompanyWebsite,
		&i.Name,
		&i.Type,
		&i.Address,
		&i.ImageUrl,
		&i.PicName,
		&i.PicContact,
		&i.PicEmail,
		&i.PicPosition,
		&i.Username,
		&i.LoginHashPassword,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateState = `-- name: UpdateState :one
UPDATE states
SET name = $1
WHERE id = $2
RETURNING id, name, created_at, updated_at
`

type UpdateStateParams struct {
	Name string    `db:"name" json:"name"`
	ID   uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateState(ctx context.Context, arg *UpdateStateParams) (*State, error) {
	row := q.db.QueryRow(ctx, updateState, arg.Name, arg.ID)
	var i State
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
