// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claim_queries.sql

package claims

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClaim = `-- name: CreateClaim :one
INSERT INTO claims (
    warranty_id, claim_no, status, claim_date, damaged_image_url,
    resolution_image_url, remarks
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
)
RETURNING id, warranty_id, claim_no, status, claim_date, damaged_image_url, resolution_image_url, remarks, created_at, updated_at
`

type CreateClaimParams struct {
	WarrantyID         uuid.UUID   `db:"warranty_id" json:"warrantyId"`
	ClaimNo            string      `db:"claim_no" json:"claimNo"`
	Status             string      `db:"status" json:"status"`
	ClaimDate          pgtype.Date `db:"claim_date" json:"claimDate"`
	DamagedImageUrl    string      `db:"damaged_image_url" json:"damagedImageUrl"`
	ResolutionImageUrl string      `db:"resolution_image_url" json:"resolutionImageUrl"`
	Remarks            pgtype.Text `db:"remarks" json:"remarks"`
}

func (q *Queries) CreateClaim(ctx context.Context, arg *CreateClaimParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, createClaim,
		arg.WarrantyID,
		arg.ClaimNo,
		arg.Status,
		arg.ClaimDate,
		arg.DamagedImageUrl,
		arg.ResolutionImageUrl,
		arg.Remarks,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.Status,
		&i.ClaimDate,
		&i.DamagedImageUrl,
		&i.ResolutionImageUrl,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteClaim = `-- name: DeleteClaim :exec
DELETE FROM claims
WHERE id = $1
`

func (q *Queries) DeleteClaim(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClaim, id)
	return err
}

const getClaimByID = `-- name: GetClaimByID :one
SELECT id, warranty_id, claim_no, status, claim_date, damaged_image_url, resolution_image_url, remarks, created_at, updated_at FROM claims
WHERE id = $1
`

func (q *Queries) GetClaimByID(ctx context.Context, id uuid.UUID) (*Claim, error) {
	row := q.db.QueryRow(ctx, getClaimByID, id)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.Status,
		&i.ClaimDate,
		&i.DamagedImageUrl,
		&i.ResolutionImageUrl,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listClaimDetails = `-- name: ListClaimDetails :many
SELECT claim_id, claim_no, status, claim_date, damaged_image_url, resolution_image_url, remarks, created_at, updated_at, customer_name, customer_email, customer_contact, car_brand, car_model, car_plate_no, car_chassis_no, warranty_image_url, installation_date, reference_no, warranty_no, car_part_name, car_part_description, allocated_film_quantity, film_allocated_date, shop_state, shop_company_name, shop_name, shop_address FROM claim_details
ORDER BY claim_date DESC
`

func (q *Queries) ListClaimDetails(ctx context.Context) ([]*ClaimDetail, error) {
	rows, err := q.db.Query(ctx, listClaimDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ClaimDetail{}
	for rows.Next() {
		var i ClaimDetail
		if err := rows.Scan(
			&i.ClaimID,
			&i.ClaimNo,
			&i.Status,
			&i.ClaimDate,
			&i.DamagedImageUrl,
			&i.ResolutionImageUrl,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerContact,
			&i.CarBrand,
			&i.CarModel,
			&i.CarPlateNo,
			&i.CarChassisNo,
			&i.WarrantyImageUrl,
			&i.InstallationDate,
			&i.ReferenceNo,
			&i.WarrantyNo,
			&i.CarPartName,
			&i.CarPartDescription,
			&i.AllocatedFilmQuantity,
			&i.FilmAllocatedDate,
			&i.ShopState,
			&i.ShopCompanyName,
			&i.ShopName,
			&i.ShopAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaims = `-- name: ListClaims :many
SELECT id, warranty_id, claim_no, status, claim_date, damaged_image_url, resolution_image_url, remarks, created_at, updated_at FROM claims
ORDER BY claim_date DESC
`

func (q *Queries) ListClaims(ctx context.Context) ([]*Claim, error) {
	rows, err := q.db.Query(ctx, listClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.WarrantyID,
			&i.ClaimNo,
			&i.Status,
			&i.ClaimDate,
			&i.DamagedImageUrl,
			&i.ResolutionImageUrl,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClaim = `-- name: UpdateClaim :one
UPDATE claims
SET warranty_id = $1, claim_no = $2, status = $3, claim_date = $4, damaged_image_url = $5,
    resolution_image_url = $6, remarks = $7
WHERE id = $8
RETURNING id, warranty_id, claim_no, status, claim_date, damaged_image_url, resolution_image_url, remarks, created_at, updated_at
`

type UpdateClaimParams struct {
	WarrantyID         uuid.UUID   `db:"warranty_id" json:"warrantyId"`
	ClaimNo            string      `db:"claim_no" json:"claimNo"`
	Status             string      `db:"status" json:"status"`
	ClaimDate          pgtype.Date `db:"claim_date" json:"claimDate"`
	DamagedImageUrl    string      `db:"damaged_image_url" json:"damagedImageUrl"`
	ResolutionImageUrl string      `db:"resolution_image_url" json:"resolutionImageUrl"`
	Remarks            pgtype.Text `db:"remarks" json:"remarks"`
	ID                 uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateClaim(ctx context.Context, arg *UpdateClaimParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, updateClaim,
		arg.WarrantyID,
		arg.ClaimNo,
		arg.Status,
		arg.ClaimDate,
		arg.DamagedImageUrl,
		arg.ResolutionImageUrl,
		arg.Remarks,
		arg.ID,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.Status,
		&i.ClaimDate,
		&i.DamagedImageUrl,
		&i.ResolutionImageUrl,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
