// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claims.query.sql

package claims

import (
	"context"
	"time"
)

const createClaim = `-- name: CreateClaim :one
INSERT INTO claims (
    warranty_id,
    claim_no,
    claim_date
) VALUES (
    $1, $2, $3
)
RETURNING id, warranty_id, claim_no, claim_date, is_approved, created_at, updated_at
`

type CreateClaimParams struct {
	WarrantyID int32     `db:"warranty_id" json:"warrantyId"`
	ClaimNo    string    `db:"claim_no" json:"claimNo"`
	ClaimDate  time.Time `db:"claim_date" json:"claimDate"`
}

func (q *Queries) CreateClaim(ctx context.Context, arg *CreateClaimParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, createClaim, arg.WarrantyID, arg.ClaimNo, arg.ClaimDate)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.ClaimDate,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createClaimWarrantyPart = `-- name: CreateClaimWarrantyPart :one
INSERT INTO claim_warranty_parts (
    claim_id,
    warranty_part_id,
    damaged_image_url,
    remarks,
    resolution_date,
    resolution_image_url
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, claim_id, warranty_part_id, damaged_image_url, status, remarks, resolution_date, resolution_image_url, is_approved, created_at, updated_at
`

type CreateClaimWarrantyPartParams struct {
	ClaimID            int32      `db:"claim_id" json:"claimId"`
	WarrantyPartID     int32      `db:"warranty_part_id" json:"warrantyPartId"`
	DamagedImageUrl    string     `db:"damaged_image_url" json:"damagedImageUrl"`
	Remarks            *string    `db:"remarks" json:"remarks"`
	ResolutionDate     *time.Time `db:"resolution_date" json:"resolutionDate"`
	ResolutionImageUrl *string    `db:"resolution_image_url" json:"resolutionImageUrl"`
}

func (q *Queries) CreateClaimWarrantyPart(ctx context.Context, arg *CreateClaimWarrantyPartParams) (*ClaimWarrantyPart, error) {
	row := q.db.QueryRow(ctx, createClaimWarrantyPart,
		arg.ClaimID,
		arg.WarrantyPartID,
		arg.DamagedImageUrl,
		arg.Remarks,
		arg.ResolutionDate,
		arg.ResolutionImageUrl,
	)
	var i ClaimWarrantyPart
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.WarrantyPartID,
		&i.DamagedImageUrl,
		&i.Status,
		&i.Remarks,
		&i.ResolutionDate,
		&i.ResolutionImageUrl,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getClaimByID = `-- name: GetClaimByID :one
SELECT
    id, warranty_id, claim_no, claim_date, is_approved, created_at, updated_at
FROM claims
WHERE id = $1
`

func (q *Queries) GetClaimByID(ctx context.Context, id int32) (*Claim, error) {
	row := q.db.QueryRow(ctx, getClaimByID, id)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.ClaimDate,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listClaimWarrantyPartsByClaimID = `-- name: ListClaimWarrantyPartsByClaimID :many
SELECT
    id, claim_id, warranty_part_id, damaged_image_url, status, remarks, resolution_date, resolution_image_url, is_approved, created_at, updated_at
FROM claim_warranty_parts
WHERE claim_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListClaimWarrantyPartsByClaimID(ctx context.Context, claimID int32) ([]*ClaimWarrantyPart, error) {
	rows, err := q.db.Query(ctx, listClaimWarrantyPartsByClaimID, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ClaimWarrantyPart{}
	for rows.Next() {
		var i ClaimWarrantyPart
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.WarrantyPartID,
			&i.DamagedImageUrl,
			&i.Status,
			&i.Remarks,
			&i.ResolutionDate,
			&i.ResolutionImageUrl,
			&i.IsApproved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaims = `-- name: ListClaims :many
SELECT
    id, warranty_id, claim_no, claim_date, is_approved, created_at, updated_at
FROM claims
ORDER BY created_at DESC
`

func (q *Queries) ListClaims(ctx context.Context) ([]*Claim, error) {
	rows, err := q.db.Query(ctx, listClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.WarrantyID,
			&i.ClaimNo,
			&i.ClaimDate,
			&i.IsApproved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClaim = `-- name: UpdateClaim :one
UPDATE claims
SET
    warranty_id = $2,
    claim_no = $3,
    claim_date = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, warranty_id, claim_no, claim_date, is_approved, created_at, updated_at
`

type UpdateClaimParams struct {
	ID         int32     `db:"id" json:"id"`
	WarrantyID int32     `db:"warranty_id" json:"warrantyId"`
	ClaimNo    string    `db:"claim_no" json:"claimNo"`
	ClaimDate  time.Time `db:"claim_date" json:"claimDate"`
}

func (q *Queries) UpdateClaim(ctx context.Context, arg *UpdateClaimParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, updateClaim,
		arg.ID,
		arg.WarrantyID,
		arg.ClaimNo,
		arg.ClaimDate,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.ClaimDate,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateClaimApproval = `-- name: UpdateClaimApproval :one
UPDATE claims
SET
    is_approved = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, warranty_id, claim_no, claim_date, is_approved, created_at, updated_at
`

type UpdateClaimApprovalParams struct {
	ID         int32 `db:"id" json:"id"`
	IsApproved bool  `db:"is_approved" json:"isApproved"`
}

func (q *Queries) UpdateClaimApproval(ctx context.Context, arg *UpdateClaimApprovalParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, updateClaimApproval, arg.ID, arg.IsApproved)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.ClaimDate,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateClaimWarrantyPart = `-- name: UpdateClaimWarrantyPart :one
UPDATE claim_warranty_parts
SET
    warranty_part_id = $2,
    damaged_image_url = $3,
    status = $4,
    remarks = $5,
    resolution_date = $6,
    resolution_image_url = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, claim_id, warranty_part_id, damaged_image_url, status, remarks, resolution_date, resolution_image_url, is_approved, created_at, updated_at
`

type UpdateClaimWarrantyPartParams struct {
	ID                 int32      `db:"id" json:"id"`
	WarrantyPartID     int32      `db:"warranty_part_id" json:"warrantyPartId"`
	DamagedImageUrl    string     `db:"damaged_image_url" json:"damagedImageUrl"`
	Status             string     `db:"status" json:"status"`
	Remarks            *string    `db:"remarks" json:"remarks"`
	ResolutionDate     *time.Time `db:"resolution_date" json:"resolutionDate"`
	ResolutionImageUrl *string    `db:"resolution_image_url" json:"resolutionImageUrl"`
}

func (q *Queries) UpdateClaimWarrantyPart(ctx context.Context, arg *UpdateClaimWarrantyPartParams) (*ClaimWarrantyPart, error) {
	row := q.db.QueryRow(ctx, updateClaimWarrantyPart,
		arg.ID,
		arg.WarrantyPartID,
		arg.DamagedImageUrl,
		arg.Status,
		arg.Remarks,
		arg.ResolutionDate,
		arg.ResolutionImageUrl,
	)
	var i ClaimWarrantyPart
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.WarrantyPartID,
		&i.DamagedImageUrl,
		&i.Status,
		&i.Remarks,
		&i.ResolutionDate,
		&i.ResolutionImageUrl,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateClaimWarrantyPartApproval = `-- name: UpdateClaimWarrantyPartApproval :one
UPDATE claim_warranty_parts
SET
    is_approved = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, claim_id, warranty_part_id, damaged_image_url, status, remarks, resolution_date, resolution_image_url, is_approved, created_at, updated_at
`

type UpdateClaimWarrantyPartApprovalParams struct {
	ID         int32 `db:"id" json:"id"`
	IsApproved bool  `db:"is_approved" json:"isApproved"`
}

func (q *Queries) UpdateClaimWarrantyPartApproval(ctx context.Context, arg *UpdateClaimWarrantyPartApprovalParams) (*ClaimWarrantyPart, error) {
	row := q.db.QueryRow(ctx, updateClaimWarrantyPartApproval, arg.ID, arg.IsApproved)
	var i ClaimWarrantyPart
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.WarrantyPartID,
		&i.DamagedImageUrl,
		&i.Status,
		&i.Remarks,
		&i.ResolutionDate,
		&i.ResolutionImageUrl,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
