// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claims.query.sql

package claims

import (
	"context"
	"time"

	models "github.com/kokweikhong/profilm_ewarranty/backend/internal/models"
)

const createClaim = `-- name: CreateClaim :one
INSERT INTO claims (
    warranty_id,
    claim_no,
    claim_date
) VALUES (
    $1, $2, $3
)
RETURNING id, warranty_id, claim_no, claim_date, approval_status, status, remarks, created_at, updated_at
`

type CreateClaimParams struct {
	WarrantyID int32     `db:"warranty_id" json:"warrantyId"`
	ClaimNo    string    `db:"claim_no" json:"claimNo"`
	ClaimDate  time.Time `db:"claim_date" json:"claimDate"`
}

func (q *Queries) CreateClaim(ctx context.Context, arg *CreateClaimParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, createClaim, arg.WarrantyID, arg.ClaimNo, arg.ClaimDate)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.ClaimDate,
		&i.ApprovalStatus,
		&i.Status,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createClaimWarrantyPart = `-- name: CreateClaimWarrantyPart :one
INSERT INTO claim_warranty_parts (
    claim_id,
    warranty_part_id,
    damaged_image_url,
    remarks,
    resolution_date,
    resolution_image_url
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, claim_id, warranty_part_id, damaged_image_url, status, remarks, resolution_date, resolution_image_url, approval_status, created_at, updated_at
`

type CreateClaimWarrantyPartParams struct {
	ClaimID            int32      `db:"claim_id" json:"claimId"`
	WarrantyPartID     int32      `db:"warranty_part_id" json:"warrantyPartId"`
	DamagedImageUrl    string     `db:"damaged_image_url" json:"damagedImageUrl"`
	Remarks            *string    `db:"remarks" json:"remarks"`
	ResolutionDate     *time.Time `db:"resolution_date" json:"resolutionDate"`
	ResolutionImageUrl *string    `db:"resolution_image_url" json:"resolutionImageUrl"`
}

func (q *Queries) CreateClaimWarrantyPart(ctx context.Context, arg *CreateClaimWarrantyPartParams) (*ClaimWarrantyPart, error) {
	row := q.db.QueryRow(ctx, createClaimWarrantyPart,
		arg.ClaimID,
		arg.WarrantyPartID,
		arg.DamagedImageUrl,
		arg.Remarks,
		arg.ResolutionDate,
		arg.ResolutionImageUrl,
	)
	var i ClaimWarrantyPart
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.WarrantyPartID,
		&i.DamagedImageUrl,
		&i.Status,
		&i.Remarks,
		&i.ResolutionDate,
		&i.ResolutionImageUrl,
		&i.ApprovalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getClaimByID = `-- name: GetClaimByID :one
SELECT
    id, warranty_id, claim_no, claim_date, approval_status, status, remarks, created_at, updated_at, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url
FROM claim_view
WHERE id = $1
`

func (q *Queries) GetClaimByID(ctx context.Context, id int32) (*ClaimView, error) {
	row := q.db.QueryRow(ctx, getClaimByID, id)
	var i ClaimView
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.ClaimDate,
		&i.ApprovalStatus,
		&i.Status,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShopID,
		&i.ClientName,
		&i.ClientContact,
		&i.ClientEmail,
		&i.CarBrand,
		&i.CarModel,
		&i.CarColour,
		&i.CarPlateNo,
		&i.CarChassisNo,
		&i.InstallationDate,
		&i.ReferenceNo,
		&i.WarrantyNo,
		&i.InvoiceAttachmentUrl,
	)
	return &i, err
}

const getClaimWarrantyPartsByClaimID = `-- name: GetClaimWarrantyPartsByClaimID :many
SELECT
    id, claim_id, warranty_part_id, damaged_image_url, status, remarks, resolution_date, resolution_image_url, approval_status, created_at, updated_at, installation_image_url, car_part_name, car_part_code, product_allocation_id, brand_name, type_name, series_name, product_name, film_serial_number, warranty_in_months
FROM claim_warranty_parts_view
WHERE claim_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetClaimWarrantyPartsByClaimID(ctx context.Context, claimID int32) ([]*ClaimWarrantyPartsView, error) {
	rows, err := q.db.Query(ctx, getClaimWarrantyPartsByClaimID, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ClaimWarrantyPartsView{}
	for rows.Next() {
		var i ClaimWarrantyPartsView
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.WarrantyPartID,
			&i.DamagedImageUrl,
			&i.Status,
			&i.Remarks,
			&i.ResolutionDate,
			&i.ResolutionImageUrl,
			&i.ApprovalStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstallationImageUrl,
			&i.CarPartName,
			&i.CarPartCode,
			&i.ProductAllocationID,
			&i.BrandName,
			&i.TypeName,
			&i.SeriesName,
			&i.ProductName,
			&i.FilmSerialNumber,
			&i.WarrantyInMonths,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClaims = `-- name: GetClaims :many
SELECT
    id, warranty_id, claim_no, claim_date, approval_status, status, remarks, created_at, updated_at, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url
FROM claim_view
ORDER BY created_at DESC
`

// claim_view
func (q *Queries) GetClaims(ctx context.Context) ([]*ClaimView, error) {
	rows, err := q.db.Query(ctx, getClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ClaimView{}
	for rows.Next() {
		var i ClaimView
		if err := rows.Scan(
			&i.ID,
			&i.WarrantyID,
			&i.ClaimNo,
			&i.ClaimDate,
			&i.ApprovalStatus,
			&i.Status,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShopID,
			&i.ClientName,
			&i.ClientContact,
			&i.ClientEmail,
			&i.CarBrand,
			&i.CarModel,
			&i.CarColour,
			&i.CarPlateNo,
			&i.CarChassisNo,
			&i.InstallationDate,
			&i.ReferenceNo,
			&i.WarrantyNo,
			&i.InvoiceAttachmentUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClaimsByShopID = `-- name: GetClaimsByShopID :many
SELECT
    id, warranty_id, claim_no, claim_date, approval_status, status, remarks, created_at, updated_at, shop_id, client_name, client_contact, client_email, car_brand, car_model, car_colour, car_plate_no, car_chassis_no, installation_date, reference_no, warranty_no, invoice_attachment_url
FROM claim_view
WHERE shop_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetClaimsByShopID(ctx context.Context, shopID int32) ([]*ClaimView, error) {
	rows, err := q.db.Query(ctx, getClaimsByShopID, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ClaimView{}
	for rows.Next() {
		var i ClaimView
		if err := rows.Scan(
			&i.ID,
			&i.WarrantyID,
			&i.ClaimNo,
			&i.ClaimDate,
			&i.ApprovalStatus,
			&i.Status,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShopID,
			&i.ClientName,
			&i.ClientContact,
			&i.ClientEmail,
			&i.CarBrand,
			&i.CarModel,
			&i.CarColour,
			&i.CarPlateNo,
			&i.CarChassisNo,
			&i.InstallationDate,
			&i.ReferenceNo,
			&i.WarrantyNo,
			&i.InvoiceAttachmentUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestWarrantyNoByPrefix = `-- name: GetLatestWarrantyNoByPrefix :one
SELECT
    claim_no
FROM claims
WHERE claim_no LIKE $1
ORDER BY claim_no DESC
LIMIT 1
`

func (q *Queries) GetLatestWarrantyNoByPrefix(ctx context.Context, claimNo string) (string, error) {
	row := q.db.QueryRow(ctx, getLatestWarrantyNoByPrefix, claimNo)
	var claim_no string
	err := row.Scan(&claim_no)
	return claim_no, err
}

const updateClaim = `-- name: UpdateClaim :one
UPDATE claims
SET
    warranty_id = $2,
    claim_no = $3,
    claim_date = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, warranty_id, claim_no, claim_date, approval_status, status, remarks, created_at, updated_at
`

type UpdateClaimParams struct {
	ID         int32     `db:"id" json:"id"`
	WarrantyID int32     `db:"warranty_id" json:"warrantyId"`
	ClaimNo    string    `db:"claim_no" json:"claimNo"`
	ClaimDate  time.Time `db:"claim_date" json:"claimDate"`
}

func (q *Queries) UpdateClaim(ctx context.Context, arg *UpdateClaimParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, updateClaim,
		arg.ID,
		arg.WarrantyID,
		arg.ClaimNo,
		arg.ClaimDate,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.ClaimDate,
		&i.ApprovalStatus,
		&i.Status,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateClaimApproval = `-- name: UpdateClaimApproval :one
UPDATE claims
SET
    approval_status = $2,
    remarks = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, warranty_id, claim_no, claim_date, approval_status, status, remarks, created_at, updated_at
`

type UpdateClaimApprovalParams struct {
	ID             int32                 `db:"id" json:"id"`
	ApprovalStatus models.ApprovalStatus `db:"approval_status" json:"approvalStatus"`
	Remarks        *string               `db:"remarks" json:"remarks"`
}

func (q *Queries) UpdateClaimApproval(ctx context.Context, arg *UpdateClaimApprovalParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, updateClaimApproval, arg.ID, arg.ApprovalStatus, arg.Remarks)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.ClaimDate,
		&i.ApprovalStatus,
		&i.Status,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateClaimStatus = `-- name: UpdateClaimStatus :one
UPDATE claims
SET
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, warranty_id, claim_no, claim_date, approval_status, status, remarks, created_at, updated_at
`

type UpdateClaimStatusParams struct {
	ID     int32  `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateClaimStatus(ctx context.Context, arg *UpdateClaimStatusParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, updateClaimStatus, arg.ID, arg.Status)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.WarrantyID,
		&i.ClaimNo,
		&i.ClaimDate,
		&i.ApprovalStatus,
		&i.Status,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateClaimWarrantyPart = `-- name: UpdateClaimWarrantyPart :one
UPDATE claim_warranty_parts
SET
    warranty_part_id = $2,
    damaged_image_url = $3,
    status = $4,
    remarks = $5,
    resolution_date = $6,
    resolution_image_url = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, claim_id, warranty_part_id, damaged_image_url, status, remarks, resolution_date, resolution_image_url, approval_status, created_at, updated_at
`

type UpdateClaimWarrantyPartParams struct {
	ID                 int32      `db:"id" json:"id"`
	WarrantyPartID     int32      `db:"warranty_part_id" json:"warrantyPartId"`
	DamagedImageUrl    string     `db:"damaged_image_url" json:"damagedImageUrl"`
	Status             string     `db:"status" json:"status"`
	Remarks            *string    `db:"remarks" json:"remarks"`
	ResolutionDate     *time.Time `db:"resolution_date" json:"resolutionDate"`
	ResolutionImageUrl *string    `db:"resolution_image_url" json:"resolutionImageUrl"`
}

func (q *Queries) UpdateClaimWarrantyPart(ctx context.Context, arg *UpdateClaimWarrantyPartParams) (*ClaimWarrantyPart, error) {
	row := q.db.QueryRow(ctx, updateClaimWarrantyPart,
		arg.ID,
		arg.WarrantyPartID,
		arg.DamagedImageUrl,
		arg.Status,
		arg.Remarks,
		arg.ResolutionDate,
		arg.ResolutionImageUrl,
	)
	var i ClaimWarrantyPart
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.WarrantyPartID,
		&i.DamagedImageUrl,
		&i.Status,
		&i.Remarks,
		&i.ResolutionDate,
		&i.ResolutionImageUrl,
		&i.ApprovalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateClaimWarrantyPartApproval = `-- name: UpdateClaimWarrantyPartApproval :one
UPDATE claim_warranty_parts
SET
    approval_status = $2,
    remarks = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, claim_id, warranty_part_id, damaged_image_url, status, remarks, resolution_date, resolution_image_url, approval_status, created_at, updated_at
`

type UpdateClaimWarrantyPartApprovalParams struct {
	ID             int32                 `db:"id" json:"id"`
	ApprovalStatus models.ApprovalStatus `db:"approval_status" json:"approvalStatus"`
	Remarks        *string               `db:"remarks" json:"remarks"`
}

func (q *Queries) UpdateClaimWarrantyPartApproval(ctx context.Context, arg *UpdateClaimWarrantyPartApprovalParams) (*ClaimWarrantyPart, error) {
	row := q.db.QueryRow(ctx, updateClaimWarrantyPartApproval, arg.ID, arg.ApprovalStatus, arg.Remarks)
	var i ClaimWarrantyPart
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.WarrantyPartID,
		&i.DamagedImageUrl,
		&i.Status,
		&i.Remarks,
		&i.ResolutionDate,
		&i.ResolutionImageUrl,
		&i.ApprovalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateClaimWarrantyPartStatus = `-- name: UpdateClaimWarrantyPartStatus :one
UPDATE claim_warranty_parts
SET
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, claim_id, warranty_part_id, damaged_image_url, status, remarks, resolution_date, resolution_image_url, approval_status, created_at, updated_at
`

type UpdateClaimWarrantyPartStatusParams struct {
	ID     int32  `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateClaimWarrantyPartStatus(ctx context.Context, arg *UpdateClaimWarrantyPartStatusParams) (*ClaimWarrantyPart, error) {
	row := q.db.QueryRow(ctx, updateClaimWarrantyPartStatus, arg.ID, arg.Status)
	var i ClaimWarrantyPart
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.WarrantyPartID,
		&i.DamagedImageUrl,
		&i.Status,
		&i.Remarks,
		&i.ResolutionDate,
		&i.ResolutionImageUrl,
		&i.ApprovalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
