// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package claims

import (
	"time"
)

type CarPart struct {
	ID          int32     `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Code        string    `db:"code" json:"code"`
	Description *string   `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time `db:"updated_at" json:"updatedAt"`
}

type Claim struct {
	ID         int32     `db:"id" json:"id"`
	WarrantyID int32     `db:"warranty_id" json:"warrantyId"`
	ClaimNo    string    `db:"claim_no" json:"claimNo"`
	ClaimDate  time.Time `db:"claim_date" json:"claimDate"`
	IsApproved bool      `db:"is_approved" json:"isApproved"`
	Status     string    `db:"status" json:"status"`
	Remarks    *string   `db:"remarks" json:"remarks"`
	CreatedAt  time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt  time.Time `db:"updated_at" json:"updatedAt"`
}

type ClaimView struct {
	ID                   int32     `db:"id" json:"id"`
	WarrantyID           int32     `db:"warranty_id" json:"warrantyId"`
	ClaimNo              string    `db:"claim_no" json:"claimNo"`
	ClaimDate            time.Time `db:"claim_date" json:"claimDate"`
	IsApproved           bool      `db:"is_approved" json:"isApproved"`
	Status               string    `db:"status" json:"status"`
	Remarks              *string   `db:"remarks" json:"remarks"`
	CreatedAt            time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt            time.Time `db:"updated_at" json:"updatedAt"`
	ShopID               int32     `db:"shop_id" json:"shopId"`
	ClientName           string    `db:"client_name" json:"clientName"`
	ClientContact        string    `db:"client_contact" json:"clientContact"`
	ClientEmail          string    `db:"client_email" json:"clientEmail"`
	CarBrand             string    `db:"car_brand" json:"carBrand"`
	CarModel             string    `db:"car_model" json:"carModel"`
	CarColour            string    `db:"car_colour" json:"carColour"`
	CarPlateNo           string    `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo         string    `db:"car_chassis_no" json:"carChassisNo"`
	InstallationDate     time.Time `db:"installation_date" json:"installationDate"`
	ReferenceNo          *string   `db:"reference_no" json:"referenceNo"`
	WarrantyNo           string    `db:"warranty_no" json:"warrantyNo"`
	InvoiceAttachmentUrl string    `db:"invoice_attachment_url" json:"invoiceAttachmentUrl"`
}

type ClaimWarrantyPart struct {
	ID                 int32      `db:"id" json:"id"`
	ClaimID            int32      `db:"claim_id" json:"claimId"`
	WarrantyPartID     int32      `db:"warranty_part_id" json:"warrantyPartId"`
	DamagedImageUrl    string     `db:"damaged_image_url" json:"damagedImageUrl"`
	Status             string     `db:"status" json:"status"`
	Remarks            *string    `db:"remarks" json:"remarks"`
	ResolutionDate     *time.Time `db:"resolution_date" json:"resolutionDate"`
	ResolutionImageUrl *string    `db:"resolution_image_url" json:"resolutionImageUrl"`
	IsApproved         bool       `db:"is_approved" json:"isApproved"`
	CreatedAt          time.Time  `db:"created_at" json:"createdAt"`
	UpdatedAt          time.Time  `db:"updated_at" json:"updatedAt"`
}

type ClaimWarrantyPartsView struct {
	ID                   int32      `db:"id" json:"id"`
	ClaimID              int32      `db:"claim_id" json:"claimId"`
	WarrantyPartID       int32      `db:"warranty_part_id" json:"warrantyPartId"`
	DamagedImageUrl      string     `db:"damaged_image_url" json:"damagedImageUrl"`
	Status               string     `db:"status" json:"status"`
	Remarks              *string    `db:"remarks" json:"remarks"`
	ResolutionDate       *time.Time `db:"resolution_date" json:"resolutionDate"`
	ResolutionImageUrl   *string    `db:"resolution_image_url" json:"resolutionImageUrl"`
	IsApproved           bool       `db:"is_approved" json:"isApproved"`
	CreatedAt            time.Time  `db:"created_at" json:"createdAt"`
	UpdatedAt            time.Time  `db:"updated_at" json:"updatedAt"`
	InstallationImageUrl string     `db:"installation_image_url" json:"installationImageUrl"`
	CarPartName          string     `db:"car_part_name" json:"carPartName"`
	CarPartCode          string     `db:"car_part_code" json:"carPartCode"`
	ProductAllocationID  int32      `db:"product_allocation_id" json:"productAllocationId"`
	BrandName            string     `db:"brand_name" json:"brandName"`
	TypeName             string     `db:"type_name" json:"typeName"`
	SeriesName           string     `db:"series_name" json:"seriesName"`
	ProductName          string     `db:"product_name" json:"productName"`
	FilmSerialNumber     string     `db:"film_serial_number" json:"filmSerialNumber"`
	WarrantyInMonths     int32      `db:"warranty_in_months" json:"warrantyInMonths"`
}

type MsiaState struct {
	ID        int32     `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Code      string    `db:"code" json:"code"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time `db:"updated_at" json:"updatedAt"`
}

type Product struct {
	ID               int32     `db:"id" json:"id"`
	BrandID          int32     `db:"brand_id" json:"brandId"`
	TypeID           int32     `db:"type_id" json:"typeId"`
	SeriesID         int32     `db:"series_id" json:"seriesId"`
	NameID           int32     `db:"name_id" json:"nameId"`
	WarrantyInMonths int32     `db:"warranty_in_months" json:"warrantyInMonths"`
	FilmSerialNumber string    `db:"film_serial_number" json:"filmSerialNumber"`
	FilmQuantity     int32     `db:"film_quantity" json:"filmQuantity"`
	ShipmentNumber   string    `db:"shipment_number" json:"shipmentNumber"`
	Description      string    `db:"description" json:"description"`
	IsActive         bool      `db:"is_active" json:"isActive"`
	CreatedAt        time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt        time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductAllocation struct {
	ID             int32     `db:"id" json:"id"`
	ProductID      int32     `db:"product_id" json:"productId"`
	ShopID         int32     `db:"shop_id" json:"shopId"`
	FilmQuantity   int32     `db:"film_quantity" json:"filmQuantity"`
	AllocationDate time.Time `db:"allocation_date" json:"allocationDate"`
	CreatedAt      time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt      time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductAllocationsView struct {
	AllocationID     int32     `db:"allocation_id" json:"allocationId"`
	FilmSerialNumber string    `db:"film_serial_number" json:"filmSerialNumber"`
	WarrantyInMonths int32     `db:"warranty_in_months" json:"warrantyInMonths"`
	ProductBrand     string    `db:"product_brand" json:"productBrand"`
	ProductType      string    `db:"product_type" json:"productType"`
	ProductSeries    string    `db:"product_series" json:"productSeries"`
	ProductName      string    `db:"product_name" json:"productName"`
	ShopName         string    `db:"shop_name" json:"shopName"`
	BranchCode       string    `db:"branch_code" json:"branchCode"`
	FilmQuantity     int32     `db:"film_quantity" json:"filmQuantity"`
	AllocationDate   time.Time `db:"allocation_date" json:"allocationDate"`
	CreatedAt        time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt        time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductBrand struct {
	ID          int32     `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductName struct {
	ID          int32     `db:"id" json:"id"`
	SeriesID    int32     `db:"series_id" json:"seriesId"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductSeries struct {
	ID          int32     `db:"id" json:"id"`
	TypeID      int32     `db:"type_id" json:"typeId"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time `db:"updated_at" json:"updatedAt"`
}

type ProductType struct {
	ID          int32     `db:"id" json:"id"`
	BrandID     int32     `db:"brand_id" json:"brandId"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time `db:"updated_at" json:"updatedAt"`
}

type Shop struct {
	ID                        int32     `db:"id" json:"id"`
	CompanyName               string    `db:"company_name" json:"companyName"`
	CompanyRegistrationNumber string    `db:"company_registration_number" json:"companyRegistrationNumber"`
	CompanyLicenseImageUrl    string    `db:"company_license_image_url" json:"companyLicenseImageUrl"`
	CompanyContactNumber      string    `db:"company_contact_number" json:"companyContactNumber"`
	CompanyEmail              string    `db:"company_email" json:"companyEmail"`
	CompanyWebsiteUrl         string    `db:"company_website_url" json:"companyWebsiteUrl"`
	ShopName                  string    `db:"shop_name" json:"shopName"`
	ShopAddress               string    `db:"shop_address" json:"shopAddress"`
	MsiaStateID               *int32    `db:"msia_state_id" json:"msiaStateId"`
	BranchCode                string    `db:"branch_code" json:"branchCode"`
	ShopImageUrl              string    `db:"shop_image_url" json:"shopImageUrl"`
	PicName                   string    `db:"pic_name" json:"picName"`
	PicPosition               string    `db:"pic_position" json:"picPosition"`
	PicContactNumber          string    `db:"pic_contact_number" json:"picContactNumber"`
	PicEmail                  string    `db:"pic_email" json:"picEmail"`
	IsActive                  bool      `db:"is_active" json:"isActive"`
	CreatedAt                 time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt                 time.Time `db:"updated_at" json:"updatedAt"`
}

type User struct {
	ID           int32     `db:"id" json:"id"`
	ShopID       *int32    `db:"shop_id" json:"shopId"`
	Username     string    `db:"username" json:"username"`
	PasswordHash string    `db:"password_hash" json:"passwordHash"`
	Role         string    `db:"role" json:"role"`
	CreatedAt    time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt    time.Time `db:"updated_at" json:"updatedAt"`
}

type Warranty struct {
	ID                   int32     `db:"id" json:"id"`
	ShopID               int32     `db:"shop_id" json:"shopId"`
	ClientName           string    `db:"client_name" json:"clientName"`
	ClientContact        string    `db:"client_contact" json:"clientContact"`
	ClientEmail          string    `db:"client_email" json:"clientEmail"`
	CarBrand             string    `db:"car_brand" json:"carBrand"`
	CarModel             string    `db:"car_model" json:"carModel"`
	CarColour            string    `db:"car_colour" json:"carColour"`
	CarPlateNo           string    `db:"car_plate_no" json:"carPlateNo"`
	CarChassisNo         string    `db:"car_chassis_no" json:"carChassisNo"`
	InstallationDate     time.Time `db:"installation_date" json:"installationDate"`
	ReferenceNo          *string   `db:"reference_no" json:"referenceNo"`
	WarrantyNo           string    `db:"warranty_no" json:"warrantyNo"`
	InvoiceAttachmentUrl string    `db:"invoice_attachment_url" json:"invoiceAttachmentUrl"`
	IsActive             bool      `db:"is_active" json:"isActive"`
	IsApproved           bool      `db:"is_approved" json:"isApproved"`
	CreatedAt            time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt            time.Time `db:"updated_at" json:"updatedAt"`
}

type WarrantyPart struct {
	ID                   int32     `db:"id" json:"id"`
	WarrantyID           int32     `db:"warranty_id" json:"warrantyId"`
	ProductAllocationID  int32     `db:"product_allocation_id" json:"productAllocationId"`
	CarPartID            int32     `db:"car_part_id" json:"carPartId"`
	InstallationImageUrl string    `db:"installation_image_url" json:"installationImageUrl"`
	IsApproved           bool      `db:"is_approved" json:"isApproved"`
	CreatedAt            time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt            time.Time `db:"updated_at" json:"updatedAt"`
}
