// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package claims

import (
	"context"
)

type Querier interface {
	CreateClaim(ctx context.Context, arg *CreateClaimParams) (*Claim, error)
	CreateClaimWarrantyPart(ctx context.Context, arg *CreateClaimWarrantyPartParams) (*ClaimWarrantyPart, error)
	GetClaimByID(ctx context.Context, id int32) (*Claim, error)
	ListClaimWarrantyPartsByClaimID(ctx context.Context, claimID int32) ([]*ClaimWarrantyPart, error)
	ListClaims(ctx context.Context) ([]*Claim, error)
	UpdateClaim(ctx context.Context, arg *UpdateClaimParams) (*Claim, error)
	UpdateClaimApproval(ctx context.Context, arg *UpdateClaimApprovalParams) (*Claim, error)
	UpdateClaimWarrantyPart(ctx context.Context, arg *UpdateClaimWarrantyPartParams) (*ClaimWarrantyPart, error)
	UpdateClaimWarrantyPartApproval(ctx context.Context, arg *UpdateClaimWarrantyPartApprovalParams) (*ClaimWarrantyPart, error)
}

var _ Querier = (*Queries)(nil)
