// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package claims

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClaim(ctx context.Context, arg *CreateClaimParams) (*Claim, error)
	DeleteClaim(ctx context.Context, id uuid.UUID) error
	GetClaimByID(ctx context.Context, id uuid.UUID) (*Claim, error)
	ListClaimDetails(ctx context.Context) ([]*ClaimDetail, error)
	ListClaims(ctx context.Context) ([]*Claim, error)
	UpdateClaim(ctx context.Context, arg *UpdateClaimParams) (*Claim, error)
}

var _ Querier = (*Queries)(nil)
