// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package claims

import (
	"context"
)

type Querier interface {
	CreateClaim(ctx context.Context, arg *CreateClaimParams) (*Claim, error)
	CreateClaimWarrantyPart(ctx context.Context, arg *CreateClaimWarrantyPartParams) (*ClaimWarrantyPart, error)
	GetClaimByID(ctx context.Context, id int32) (*ClaimView, error)
	GetClaimWarrantyPartsByClaimID(ctx context.Context, claimID int32) ([]*ClaimWarrantyPartsView, error)
	// claim_view
	GetClaims(ctx context.Context) ([]*ClaimView, error)
	GetClaimsByShopID(ctx context.Context, shopID int32) ([]*ClaimView, error)
	GetLatestWarrantyNoByPrefix(ctx context.Context, claimNo string) (string, error)
	UpdateClaim(ctx context.Context, arg *UpdateClaimParams) (*Claim, error)
	UpdateClaimApproval(ctx context.Context, arg *UpdateClaimApprovalParams) (*Claim, error)
	UpdateClaimStatus(ctx context.Context, arg *UpdateClaimStatusParams) (*Claim, error)
	UpdateClaimWarrantyPart(ctx context.Context, arg *UpdateClaimWarrantyPartParams) (*ClaimWarrantyPart, error)
	UpdateClaimWarrantyPartApproval(ctx context.Context, arg *UpdateClaimWarrantyPartApprovalParams) (*ClaimWarrantyPart, error)
	UpdateClaimWarrantyPartStatus(ctx context.Context, arg *UpdateClaimWarrantyPartStatusParams) (*ClaimWarrantyPart, error)
}

var _ Querier = (*Queries)(nil)
