// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	GetUserByID(ctx context.Context, id int32) (*User, error)
	GetUserByUsername(ctx context.Context, username string) (*User, error)
	UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
